#![allow(unused_imports)] // TODO EU5: remove this when ready
use std::sync::LazyLock;

use crate::effect::Effect;
use crate::effect_validation::*;
use crate::eu5::effect_validation::*;
use crate::everything::Everything;
use crate::helpers::TigerHashMap;
use crate::item::Item;
use crate::scopes::*;
use crate::token::Token;

use Effect::*;

pub fn scope_effect(name: &Token, _data: &Everything) -> Option<(Scopes, Effect)> {
    let name_lc = name.as_str().to_ascii_lowercase();
    SCOPE_EFFECT_MAP.get(&*name_lc).copied()
}

/// A hashed version of [`SCOPE_EFFECT`], for quick lookup by effect name.
static SCOPE_EFFECT_MAP: LazyLock<TigerHashMap<&'static str, (Scopes, Effect)>> =
    LazyLock::new(|| {
        let mut hash = TigerHashMap::default();
        for (from, s, effect) in SCOPE_EFFECT.iter().copied() {
            hash.insert(s, (from, effect));
        }
        hash
    });

// See `effects.log` from the game data dumps
const SCOPE_EFFECT: &[(Scopes, &str, Effect)] = &[
    // TODO: EU5 fill in UncheckedTodo entries and generally verify table
    (Scopes::None, "abandon_colonial_charter", Scope(Scopes::ColonialCharter)),
    (Scopes::Country, "abandon_location", Scope(Scopes::Location)),
    (Scopes::None, "activate_situation", Scope(Scopes::Situation)),
    (Scopes::Country, "add_accepted_culture", Scope(Scopes::Culture)),
    (Scopes::ColonialCharter, "add_additional_migration", UncheckedTodo),
    (Scopes::Character, "add_adm", UncheckedTodo),
    (Scopes::Country, "add_antagonism", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_army_tradition", UncheckedTodo),
    (Scopes::Character, "add_artist_skill", UncheckedTodo),
    (Scopes::Country, "add_avatar", Scope(Scopes::Avatar)),
    (Scopes::War, "add_bonus_warscore", UncheckedTodo),
    (Scopes::Siege, "add_breach", UncheckedTodo),
    (Scopes::Country, "add_casus_belli", UncheckedTodo),
    (Scopes::Character, "add_character_modifier", UncheckedTodo),
    (Scopes::Country, "add_colonial_claim", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_cooldown", UncheckedTodo),
    (Scopes::Location, "add_core", Scope(Scopes::Country)),
    (Scopes::Country, "add_country_modifier", UncheckedTodo),
    (
        Scopes::InternationalOrganization,
        "add_country_to_international_organization",
        Scope(Scopes::Country),
    ),
    (
        Scopes::InternationalOrganization,
        "add_country_to_international_organization_no_update",
        Scope(Scopes::Country),
    ),
    (Scopes::Culture, "add_cultural_influence", UncheckedTodo),
    (Scopes::Culture, "add_cultural_tradition", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_devotion", UncheckedTodo),
    (Scopes::Character, "add_dip", UncheckedTodo),
    (Scopes::Country, "add_diplomats", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_doom", UncheckedTodo),
    (
        Scopes::InternationalOrganization,
        "add_enemy_to_international_organization",
        Scope(Scopes::Country),
    ),
    (Scopes::Country, "add_estate_satisfaction", UncheckedTodo),
    (Scopes::None, "add_extended_winter", Scope(Scopes::Area)),
    (Scopes::Country, "add_favors", UncheckedTodo),
    (Scopes::Character, "add_fertility", UncheckedTodo),
    (Scopes::Unit, "add_food", UncheckedTodo),
    (Scopes::Unit, "add_food_percentage", UncheckedTodo),
    (Scopes::Country, "add_god", Scope(Scopes::God)),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_gold", UncheckedTodo),
    (Scopes::Country, "add_gold_to_estate", UncheckedTodo),
    (Scopes::Market, "add_goods_supply", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "add_government_power",
        UncheckedTodo,
    ),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_harmony", UncheckedTodo),
    (Scopes::Country, "add_historical_rival", Scope(Scopes::Country)),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_honor", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_horde_unity", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_inflation", UncheckedTodo),
    (Scopes::None, "add_internal_flag", UncheckedTodo),
    (Scopes::Religion, "add_international_organization", Scope(Scopes::InternationalOrganization)),
    (Scopes::InternationalOrganization, "add_international_organization_modifier", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_karma", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_legitimacy", UncheckedTodo),
    (Scopes::Country, "add_liberty_desire", UncheckedTodo),
    (Scopes::Country, "add_location_as_core", Scope(Scopes::Location)),
    (Scopes::Location, "add_location_modifier", UncheckedTodo),
    (
        Scopes::InternationalOrganization,
        "add_location_to_international_organization",
        Scope(Scopes::Location),
    ),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_manpower", UncheckedTodo),
    (Scopes::Mercenary, "add_mercenary_modifier", UncheckedTodo),
    (Scopes::Market, "add_merchant_power", UncheckedTodo),
    (Scopes::None, "add_migration", UncheckedTodo),
    (Scopes::Character, "add_mil", UncheckedTodo),
    (Scopes::Unit, "add_morale", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_navy_tradition", UncheckedTodo),
    (Scopes::Country, "add_opinion", UncheckedTodo),
    (Scopes::Country, "add_policy", Scope(Scopes::Policy)),
    (
        Scopes::InternationalOrganization,
        "add_policy_to_international_organization",
        Scope(Scopes::Policy),
    ),
    (Scopes::Country, "add_policy_wanted_by_estate", UncheckedTodo),
    (Scopes::Location, "add_pop", UncheckedTodo),
    (Scopes::Pop, "add_pop_satisfaction", UncheckedTodo),
    (Scopes::Pop, "add_pop_size", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_prestige", UncheckedTodo),
    (Scopes::Province, "add_province_modifier", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_purity", UncheckedTodo),
    (Scopes::Character, "add_random_trait_from_category", UncheckedTodo),
    (Scopes::Rebels, "add_rebel_modifier", UncheckedTodo),
    (Scopes::Rebels, "add_rebel_progress", UncheckedTodo),
    (Scopes::Country, "add_reform", Scope(Scopes::GovernmentReform)),
    (Scopes::Religion, "add_reform_desire", UncheckedTodo),
    (Scopes::Religion, "add_religion_modifier", UncheckedTodo),
    (Scopes::Country, "add_religious_aspect", Scope(Scopes::ReligiousAspect)),
    (Scopes::Country, "add_religious_focus", Scope(Scopes::ReligiousFocus)),
    (Scopes::Country, "add_religious_focus_progress", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "add_religious_influence",
        UncheckedTodo,
    ),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "add_republican_tradition",
        UncheckedTodo,
    ),
    (Scopes::Country, "add_research_progress", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_righteousness", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_rite_power", UncheckedTodo),
    (Scopes::Country, "add_rival", Scope(Scopes::Country)),
    (Scopes::Location, "add_road_to", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_sailors", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_self_control", UncheckedTodo),
    (Scopes::Country, "add_spy_network", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_stability", UncheckedTodo),
    (Scopes::Unit, "add_subunit", Scope(Scopes::UnitType)),
    (Scopes::SubUnit, "add_subunit_experience", UncheckedTodo),
    (Scopes::SubUnit, "add_subunit_morale", UncheckedTodo),
    (Scopes::SubUnit, "add_subunit_strength", UncheckedTodo),
    (Scopes::SubUnit, "add_subunit_strength_percentage", UncheckedTodo),
    (Scopes::Market, "add_temporary_demand", UncheckedTodo),
    (Scopes::Cabinet, "add_to_cabinet", Scope(Scopes::Character)),
    (Scopes::None, "add_to_global_variable_list", UncheckedTodo),
    (Scopes::None, "add_to_list", UncheckedTodo),
    (Scopes::None, "add_to_local_variable_list", UncheckedTodo),
    (Scopes::None, "add_to_temporary_list", UncheckedTodo),
    (Scopes::None, "add_to_variable_list", UncheckedTodo),
    (Scopes::Country, "add_tolerated_culture", Scope(Scopes::Culture)),
    (Scopes::Character, "add_trait", Scope(Scopes::Trait)),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "add_tribal_cohesion",
        UncheckedTodo,
    ),
    (Scopes::Country, "add_truce_with", UncheckedTodo),
    (Scopes::Country, "add_trust", UncheckedTodo),
    (Scopes::Unit, "add_unit_modifier", UncheckedTodo),
    (Scopes::Location, "add_vfx", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_war_exhaustion", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "add_yanantin", UncheckedTodo),
    (Scopes::Country, "add_yearly_gold", UncheckedTodo),
    (Scopes::Country, "add_yearly_manpower", UncheckedTodo),
    (Scopes::Country, "add_yearly_sailors", UncheckedTodo),
    (Scopes::Character, "adopt_character", Scope(Scopes::Character)),
    (Scopes::Country, "align_societal_values_to", Scope(Scopes::Country)),
    (Scopes::Country, "annex_country", UncheckedTodo),
    (Scopes::None, "assert_if", UncheckedTodo),
    (Scopes::None, "assert_read", UncheckedTodo),
    (Scopes::Mercenary, "become_hired_by", Scope(Scopes::Country)),
    (Scopes::Country, "block_treaties", Scope(Scopes::Country)),
    (Scopes::Country, "bribe_estate", UncheckedTodo),
    (Scopes::Country, "bypass_mission_task", Scope(Scopes::MissionTask)),
    (Scopes::Country, "cancel_area_exploration", Scope(Scopes::Area)),
    (Scopes::None, "cancel_exploration", Scope(Scopes::Exploration)),
    (Scopes::None, "cancel_loan", Scope(Scopes::Loan)),
    (Scopes::Country, "cancel_subject", Scope(Scopes::Country)),
    (Scopes::Trade, "cancel_trade", UncheckedTodo),
    (Scopes::Country, "change_annexation_progress", UncheckedTodo),
    (Scopes::WorkOfArt, "change_art_quality", UncheckedTodo),
    (Scopes::Trade, "change_assigned_merchant_capacity", UncheckedTodo),
    (Scopes::Building, "change_building_level", UncheckedTodo),
    (Scopes::Location, "change_building_level_in_location", UncheckedTodo),
    (Scopes::Building, "change_building_owner", Scope(Scopes::Country)),
    (Scopes::Country, "change_casus_belli_creation_progress", UncheckedTodo),
    (Scopes::Character, "change_character_allegiance", Scope(Scopes::Rebels)),
    (Scopes::Character, "change_character_culture", Scope(Scopes::Culture)),
    (Scopes::Character, "change_character_estate", Scope(Scopes::EstateType)),
    (Scopes::Character, "change_character_religion", Scope(Scopes::Religion)),
    (Scopes::ColonialCharter, "change_colonial_charter_owner", Scope(Scopes::Country)),
    (Scopes::Location, "change_control", UncheckedTodo),
    (Scopes::Country, "change_country_adjective", UncheckedTodo),
    (Scopes::Country, "change_country_color", UncheckedTodo),
    (Scopes::Country, "change_country_dynastic_name", UncheckedTodo),
    (Scopes::Country, "change_country_flag", UncheckedTodo),
    (Scopes::Country, "change_country_name", UncheckedTodo),
    (Scopes::Country, "change_country_tag", UncheckedTodo),
    (Scopes::Country, "change_country_type", UncheckedTodo),
    (Scopes::Culture, "change_cultural_view", UncheckedTodo),
    (Scopes::Country, "change_culture", Scope(Scopes::Culture)),
    (Scopes::Location, "change_development", UncheckedTodo),
    (Scopes::Location.union(Scopes::SubUnit), "change_disease_presence", UncheckedTodo),
    (Scopes::Character, "change_dynasty", Scope(Scopes::Dynasty)),
    (Scopes::Exploration, "change_exploration_progress", UncheckedTodo),
    (Scopes::Country, "change_explorer", UncheckedTodo),
    (Scopes::Character, "change_father", Scope(Scopes::Character)),
    (Scopes::Location, "change_garrison_size", UncheckedTodo),
    (Scopes::None, "change_global_variable", UncheckedTodo),
    (Scopes::Country, "change_government_type", Scope(Scopes::Government)),
    (Scopes::Country, "change_heir_selection", Scope(Scopes::HeirSelection)),
    (Scopes::Location, "change_institution_progress", UncheckedTodo),
    (Scopes::Location, "change_integration_level", UncheckedTodo),
    (Scopes::Location, "change_integration_progress", UncheckedTodo),
    (Scopes::Culture, "change_language", Scope(Scopes::Dialect)),
    (Scopes::Loan, "change_loan_amount", UncheckedTodo),
    (Scopes::Loan, "change_loan_borrower", Scope(Scopes::Country)),
    (Scopes::Loan, "change_loan_interest", UncheckedTodo),
    (Scopes::Loan, "change_loan_owner", Scope(Scopes::Country)),
    (Scopes::None, "change_local_variable", UncheckedTodo),
    (Scopes::Location, "change_location_controller", Scope(Scopes::Country)),
    (Scopes::Location, "change_location_owner", Scope(Scopes::Country)),
    (Scopes::Location, "change_location_rank", Scope(Scopes::LocationRank)),
    (Scopes::Location, "change_maritime_presence_power", UncheckedTodo),
    (Scopes::Location, "change_max_raw_material_workers", UncheckedTodo),
    (Scopes::Character, "change_mother", Scope(Scopes::Character)),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "change_parliament_issue_support",
        UncheckedTodo,
    ),
    (Scopes::Country, "change_player", Scope(Scopes::Country)),
    (Scopes::Pop, "change_pop_allegiance", Scope(Scopes::Rebels)),
    (Scopes::Pop, "change_pop_culture", Scope(Scopes::Culture)),
    (Scopes::Pop, "change_pop_owner", Scope(Scopes::Country)),
    (Scopes::Pop, "change_pop_religion", Scope(Scopes::Religion)),
    (Scopes::Pop, "change_pop_type", Scope(Scopes::PopType)),
    (Scopes::Privateer, "change_privateer_owner", Scope(Scopes::Country)),
    (Scopes::Privateer, "change_privateer_power", UncheckedTodo),
    (Scopes::Location, "change_prosperity", UncheckedTodo),
    (Scopes::Province, "change_province_food", UncheckedTodo),
    (Scopes::Province, "change_province_food_percentage", UncheckedTodo),
    (Scopes::Province, "change_province_integration", UncheckedTodo),
    (Scopes::Province, "change_province_owner", Scope(Scopes::Country)),
    (Scopes::Location, "change_raw_material", Scope(Scopes::Goods)),
    (Scopes::Country, "change_religion", Scope(Scopes::Religion)),
    (Scopes::Religion, "change_religion_view", UncheckedTodo),
    (Scopes::Country, "change_societal_value", UncheckedTodo),
    (Scopes::Country, "change_subject_type", Scope(Scopes::SubjectType)),
    (Scopes::SubUnit, "change_subunit_type", Scope(Scopes::UnitType)),
    (Scopes::Unit, "change_unit_owner", Scope(Scopes::Country)),
    (Scopes::None, "change_variable", UncheckedTodo),
    (Scopes::None, "clamp_global_variable", UncheckedTodo),
    (Scopes::None, "clamp_local_variable", UncheckedTodo),
    (Scopes::None, "clamp_variable", UncheckedTodo),
    (Scopes::None, "clear_global_variable_list", UncheckedTodo),
    (Scopes::None, "clear_local_variable_list", UncheckedTodo),
    (Scopes::None, "clear_saved_scope", UncheckedTodo),
    (Scopes::None, "clear_variable_list", UncheckedTodo),
    (Scopes::None, "close_all_views", UncheckedTodo),
    (Scopes::Country, "complete_mission_task", Scope(Scopes::MissionTask)),
    (Scopes::None, "conditional_effect", UncheckedTodo),
    (Scopes::Location, "construct_building", UncheckedTodo),
    (Scopes::Location, "construct_estate_building", UncheckedTodo),
    (Scopes::Location, "construct_location_rank", Scope(Scopes::LocationRank)),
    (Scopes::Location, "construct_rgo_upgrade", UncheckedTodo),
    (Scopes::Country, "construct_road", UncheckedTodo),
    (Scopes::None, "copy_country_color", Scope(Scopes::Country)),
    (Scopes::None, "copy_country_flag", Scope(Scopes::Country)),
    (Scopes::None, "copy_country_name_and_adjective", Scope(Scopes::Country)),
    (Scopes::Province, "create_army_country_from_province", Scope(Scopes::Country)),
    (Scopes::Location, "create_army_country_in_location", Scope(Scopes::Country)),
    (Scopes::Location, "create_art", Scope(Scopes::WorkOfArt)),
    (Scopes::Location, "create_building_country_in_location", Scope(Scopes::Country)),
    (Scopes::Country, "create_character", Scope(Scopes::Character)),
    (Scopes::Country, "create_colonial_charter", UncheckedTodo),
    (Scopes::Country, "create_country_from_cores_in_our_locations", Scope(Scopes::Country)),
    (Scopes::Location, "create_country_from_location", Scope(Scopes::Country)),
    (Scopes::Location, "create_dynasty_from_location", UncheckedTodo),
    (Scopes::Country, "create_estate_loan", Scope(Scopes::Loan)),
    (Scopes::None, "create_holy_site", Scope(Scopes::HolySite)),
    (Scopes::None, "create_international_organization", Scope(Scopes::InternationalOrganization)),
    (Scopes::Province, "create_location_country_from_province", Scope(Scopes::Country)),
    (Scopes::None, "create_market", UncheckedTodo),
    (Scopes::None, "create_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::Country, "create_named_dynasty", UncheckedTodo),
    (Scopes::Province, "create_navy_country_from_province", Scope(Scopes::Country)),
    (Scopes::Location, "create_navy_country_in_location", Scope(Scopes::Country)),
    (Scopes::Location, "create_num_sub_unit", UncheckedTodo),
    (Scopes::Location, "create_num_sub_unit_of_category", UncheckedTodo),
    (Scopes::Country, "create_rebel", Scope(Scopes::Rebels)),
    (Scopes::None, "create_relation", UncheckedTodo),
    (Scopes::None, "create_route", UncheckedTodo),
    (Scopes::Location, "create_sub_unit", Scope(Scopes::UnitType)),
    (Scopes::Location, "create_sub_unit_of_category", Scope(Scopes::SubUnitCategory)),
    (Scopes::Location, "create_sub_unit_with_owner", UncheckedTodo),
    (Scopes::Country, "create_trade", UncheckedTodo),
    (Scopes::Country, "create_union", Scope(Scopes::Country)),
    (Scopes::None, "custom_description", UncheckedTodo),
    (Scopes::None, "custom_description_no_bullet", UncheckedTodo),
    (Scopes::None, "custom_label", UncheckedTodo),
    (Scopes::None, "custom_tooltip", UncheckedTodo),
    (Scopes::Unit, "damage_unit_morale_percent", UncheckedTodo),
    (Scopes::Unit, "damage_unit_percent", UncheckedTodo),
    (Scopes::None, "debug_log", UncheckedTodo),
    (Scopes::None, "debug_log_date", UncheckedTodo),
    (Scopes::None, "debug_log_scopes", UncheckedTodo),
    (Scopes::Country, "declare_war", Scope(Scopes::Country)),
    (Scopes::Country, "declare_war_with_cb", UncheckedTodo),
    (Scopes::Location, "destroy_all_buildings_of_type", Scope(Scopes::BuildingType)),
    (Scopes::None, "destroy_art", Scope(Scopes::WorkOfArt)),
    (Scopes::Location, "destroy_building", Scope(Scopes::Building)),
    (Scopes::None, "destroy_colonial_charter", Scope(Scopes::ColonialCharter)),
    (Scopes::None, "destroy_holy_site", Scope(Scopes::HolySite)),
    (Scopes::Country, "destroy_international_organization", UncheckedTodo),
    (Scopes::None, "destroy_international_organization_no_instigator", UncheckedTodo),
    (Scopes::Market, "destroy_market", UncheckedTodo),
    (Scopes::None, "destroy_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::None, "destroy_pop", Scope(Scopes::Pop)),
    (Scopes::None, "destroy_rebel", Scope(Scopes::Rebels)),
    (Scopes::SubUnit, "destroy_subunit", UncheckedTodo),
    (Scopes::Unit, "destroy_unit", UncheckedTodo),
    (Scopes::Country, "discover_area", Scope(Scopes::Area)),
    (Scopes::Location, "discover_location", Scope(Scopes::Country)),
    (Scopes::Country, "dismiss_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::Area, "dismiss_privateer", Scope(Scopes::Country)),
    (Scopes::Character, "divorce_character", Scope(Scopes::Character)),
    (Scopes::Country, "drop_antagonism_bomb", UncheckedTodo),
    (Scopes::None, "else", UncheckedTodo),
    (Scopes::None, "else_if", UncheckedTodo),
    (Scopes::Religion, "enable_religion", UncheckedTodo),
    (Scopes::Country, "end_mission", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "end_parliament", UncheckedTodo),
    (Scopes::None, "end_situation", Scope(Scopes::Situation)),
    (Scopes::InternationalOrganization.union(Scopes::Situation), "end_vote", UncheckedTodo),
    (Scopes::None, "error_log", UncheckedTodo),
    (Scopes::Estate, "estate_add_gold", UncheckedTodo),
    (Scopes::Unit, "execute_prisoners", UncheckedTodo),
    (Scopes::None, "execute_propose_effect", UncheckedTodo),
    (Scopes::Country, "extend_regency", UncheckedTodo),
    (
        Scopes::InternationalOrganization.union(Scopes::Situation),
        "finalize_resolution",
        Scope(Scopes::Resolution),
    ),
    (Scopes::None, "find_route", UncheckedTodo),
    (Scopes::None, "fire_generic_action", UncheckedTodo),
    (Scopes::Location, "floodfill_locations", UncheckedTodo),
    (Scopes::None, "force_city_gfx_rebuild", Scope(Scopes::Location)),
    (Scopes::None, "force_recalc_country_active_status", Scope(Scopes::Country)),
    (Scopes::None, "force_refresh_culture_and_religion", Scope(Scopes::Location)),
    (Scopes::Country, "force_union", Scope(Scopes::Country)),
    (Scopes::Country, "form_country", Scope(Scopes::FormableCountry)),
    (Scopes::Country, "form_new_culture", UncheckedTodo),
    (Scopes::Character, "found_dynasty", UncheckedTodo),
    (Scopes::Siege, "garrison_sortie", UncheckedTodo),
    (Scopes::Country, "give_loan", Scope(Scopes::Loan)),
    (Scopes::Country, "grant_estate_privilege", Scope(Scopes::EstatePrivilege)),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "grant_parliament_agenda",
        Scope(Scopes::ParliamentAgenda),
    ),
    (Scopes::Country, "grant_parliament_agenda_for_estate", Scope(Scopes::EstateType)),
    (
        Scopes::InternationalOrganization,
        "grant_parliament_agenda_for_special_status",
        Scope(Scopes::SpecialStatus),
    ),
    (Scopes::None, "hidden_effect", UncheckedTodo),
    (Scopes::Country, "hire_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::Unit, "hire_prisoners_as_mercenaries", UncheckedTodo),
    (Scopes::Area, "hire_privateer", Scope(Scopes::Country)),
    (Scopes::None, "if", UncheckedTodo),
    (Scopes::Character, "impregnate", Scope(Scopes::Character)),
    (
        Scopes::InternationalOrganization,
        "international_organization_add_special_status",
        UncheckedTodo,
    ),
    (
        Scopes::None,
        "international_organization_chooses_new_leader",
        Scope(Scopes::InternationalOrganization),
    ),
    (
        Scopes::InternationalOrganization,
        "international_organization_remove_special_status",
        UncheckedTodo,
    ),
    (Scopes::Country, "join_war_against", UncheckedTodo),
    (Scopes::Country, "join_war_as_attacker", UncheckedTodo),
    (Scopes::Country, "join_war_as_defender", UncheckedTodo),
    (Scopes::Country, "join_war_with", UncheckedTodo),
    (Scopes::None, "kill_character", Scope(Scopes::Character)),
    (Scopes::None, "kill_character_silently", Scope(Scopes::Character)),
    (Scopes::Country, "leave_war", UncheckedTodo),
    (Scopes::Country, "lift_fog_of_war", Scope(Scopes::Country)),
    (Scopes::Unit, "lock_unit", UncheckedTodo),
    (Scopes::Country.union(Scopes::Unit), "loot_location", Scope(Scopes::Location)),
    (Scopes::Character, "make_saint", Scope(Scopes::Country)),
    (Scopes::Character, "make_saint_in_character_religion", Scope(Scopes::Country)),
    (Scopes::Country, "make_subject_of", UncheckedTodo),
    (Scopes::Unit, "make_unit_available_for_hire", Scope(Scopes::Mercenary)),
    (Scopes::Character, "marry_character", Scope(Scopes::Character)),
    (Scopes::Country, "merge_culture_group", Scope(Scopes::CultureGroup)),
    (Scopes::WorkOfArt, "move_art", Scope(Scopes::Location)),
    (Scopes::Character, "move_country", Scope(Scopes::Country)),
    (Scopes::Unit, "move_prisoners_to_safety", UncheckedTodo),
    (Scopes::Unit, "move_to_assist_on_adjacent_combat", UncheckedTodo),
    (Scopes::Country, "ordered_accepted_culture", Scope(Scopes::Culture)),
    (Scopes::Country, "ordered_active_disaster", Scope(Scopes::Disaster)),
    (Scopes::None, "ordered_active_estate", Scope(Scopes::EstateType)),
    (
        Scopes::InternationalOrganization.union(Scopes::Situation),
        "ordered_active_resolution",
        Scope(Scopes::ActiveResolution),
    ),
    (Scopes::Area, "ordered_adjacent_ports_to_area", Scope(Scopes::Location)),
    (Scopes::HeirSelection, "ordered_allowed_estate_in_heir_selection", Scope(Scopes::EstateType)),
    (Scopes::Character, "ordered_ancestor", Scope(Scopes::Character)),
    (Scopes::None, "ordered_area", Scope(Scopes::Area)),
    (Scopes::Region, "ordered_area_in_region", Scope(Scopes::Area)),
    (Scopes::Country, "ordered_area_with_core", Scope(Scopes::Area)),
    (Scopes::Country, "ordered_area_with_owned_province", Scope(Scopes::Area)),
    (Scopes::Country, "ordered_army", Scope(Scopes::Unit)),
    (Scopes::Country, "ordered_artist", Scope(Scopes::Character)),
    (Scopes::War, "ordered_attacker", Scope(Scopes::Country)),
    (Scopes::God, "ordered_avatar_for_god", Scope(Scopes::Avatar)),
    (Scopes::Siege, "ordered_besieging_unit", Scope(Scopes::Unit)),
    (Scopes::Country, "ordered_border_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_buildable_building_type", Scope(Scopes::BuildingType)),
    (Scopes::None, "ordered_building_type", Scope(Scopes::BuildingType)),
    (Scopes::Location, "ordered_buildings_in_location", Scope(Scopes::Building)),
    (Scopes::Country, "ordered_cabinet", Scope(Scopes::Cabinet)),
    (Scopes::Country, "ordered_cabinet_action", Scope(Scopes::CabinetAction)),
    (Scopes::Country, "ordered_cabinet_character", Scope(Scopes::Character)),
    (Scopes::Country, "ordered_cardinal_in_country", Scope(Scopes::Cardinal)),
    (Scopes::Religion, "ordered_cardinal_in_religion", Scope(Scopes::Cardinal)),
    (Scopes::Country, "ordered_casus_belli_on_us", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_casus_belli_target", Scope(Scopes::Country)),
    (Scopes::CombatSide, "ordered_center", Scope(Scopes::SubUnit)),
    (Scopes::Country, "ordered_character", Scope(Scopes::Character)),
    (Scopes::Dynasty, "ordered_character_in_dynasty", Scope(Scopes::Character)),
    (Scopes::Rebels, "ordered_character_supporting_rebel", Scope(Scopes::Character)),
    (Scopes::Character, "ordered_child", Scope(Scopes::Character)),
    (Scopes::Character, "ordered_close_relative", Scope(Scopes::Character)),
    (Scopes::Location, "ordered_coast_border_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_colonial_charter", Scope(Scopes::ColonialCharter)),
    (
        Scopes::Country,
        "ordered_colonial_claim_province_definition",
        Scope(Scopes::ProvinceDefinition),
    ),
    (Scopes::None, "ordered_colonial_country", Scope(Scopes::Country)),
    (Scopes::None, "ordered_colonial_overlord", Scope(Scopes::Country)),
    (Scopes::None, "ordered_colonial_top_overlord", Scope(Scopes::Country)),
    (Scopes::Location, "ordered_connected_location", Scope(Scopes::Location)),
    (Scopes::BuildingType, "ordered_construction_material_for_building_type", Scope(Scopes::Goods)),
    (Scopes::None, "ordered_continent", Scope(Scopes::Continent)),
    (Scopes::Country, "ordered_controlled_location", Scope(Scopes::Location)),
    (Scopes::Location, "ordered_core_in_location", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_core_location", Scope(Scopes::Location)),
    (Scopes::None, "ordered_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_annexing_us", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_at_war_with", Scope(Scopes::Country)),
    (Scopes::Culture, "ordered_country_in_culture", Scope(Scopes::Country)),
    (Scopes::CultureGroup, "ordered_country_in_culture_group", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_in_diplomatic_range", Scope(Scopes::Country)),
    (Scopes::Dynasty, "ordered_country_in_dynasty", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_in_hierarchy", Scope(Scopes::Country)),
    (Scopes::Religion, "ordered_country_in_religion", Scope(Scopes::Country)),
    (Scopes::Group, "ordered_country_in_religion_group", Scope(Scopes::Country)),
    (Scopes::ReligiousSchool, "ordered_country_in_religious_school", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_lent_to", Scope(Scopes::Country)),
    (Scopes::None, "ordered_country_of_country_type", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_sub_unit", Scope(Scopes::SubUnit)),
    (Scopes::Rebels, "ordered_country_supporting_rebel", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_that_can_be_called_defensively", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_that_can_be_called_offensively", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_together_in_war_with", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_we_are_annexing", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_country_with_antagonism_against_us", Scope(Scopes::Country)),
    (
        Scopes::Location
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Area)
            .union(Scopes::Region)
            .union(Scopes::SubContinent)
            .union(Scopes::Continent),
        "ordered_country_with_capital_in_geography",
        Scope(Scopes::Country),
    ),
    (Scopes::Religion, "ordered_country_with_cardinals", Scope(Scopes::Country)),
    (
        Scopes::Country,
        "ordered_country_with_coalition_grade_antagonism_against_us",
        Scope(Scopes::Country),
    ),
    (
        Scopes::InternationalOrganization,
        "ordered_country_with_special_status_of_type",
        Scope(Scopes::Country),
    ),
    (Scopes::None, "ordered_country_with_succession_law", Scope(Scopes::Country)),
    (Scopes::None, "ordered_culture", Scope(Scopes::Culture)),
    (Scopes::Culture, "ordered_culture_group", Scope(Scopes::CultureGroup)),
    (Scopes::CultureGroup, "ordered_culture_in_culture_group", Scope(Scopes::Culture)),
    (Scopes::CultureGroup, "ordered_culture_in_group", Scope(Scopes::Culture)),
    (Scopes::Country, "ordered_current_avatars", Scope(Scopes::Avatar)),
    (Scopes::Country, "ordered_current_gods", Scope(Scopes::God)),
    (Scopes::Country, "ordered_current_law", Scope(Scopes::Law)),
    (
        Scopes::InternationalOrganization,
        "ordered_current_law_in_international_organization",
        Scope(Scopes::Law),
    ),
    (Scopes::Country, "ordered_current_policy", Scope(Scopes::Policy)),
    (
        Scopes::InternationalOrganization,
        "ordered_current_policy_in_international_organization",
        Scope(Scopes::Policy),
    ),
    (Scopes::Country, "ordered_current_reforms", Scope(Scopes::GovernmentReform)),
    (Scopes::Country, "ordered_current_war", Scope(Scopes::War)),
    (Scopes::War, "ordered_defender", Scope(Scopes::Country)),
    (Scopes::Character, "ordered_descendant", Scope(Scopes::Character)),
    (Scopes::Country, "ordered_disloyal_subject", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_dynasty", Scope(Scopes::Dynasty)),
    (
        Scopes::ProvinceDefinition,
        "ordered_east_of_province_definition",
        Scope(Scopes::ProvinceDefinition),
    ),
    (Scopes::Country, "ordered_election_candidates", Scope(Scopes::Character)),
    (Scopes::Country, "ordered_enemy", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_enemy_war_leader", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_estate", Scope(Scopes::Estate)),
    (Scopes::Country, "ordered_estate_privilege", Scope(Scopes::EstatePrivilege)),
    (Scopes::Policy, "ordered_estate_type_preferring", Scope(Scopes::EstateType)),
    (Scopes::Country, "ordered_exploration_from_country", Scope(Scopes::Exploration)),
    (Scopes::Market, "ordered_export", Scope(Scopes::Trade)),
    (Scopes::Location, "ordered_export_from_location", Scope(Scopes::Location)),
    (Scopes::Location, "ordered_foreign_building_countries_in_location", Scope(Scopes::Country)),
    (Scopes::Location, "ordered_foreign_buildings_in_location", Scope(Scopes::Building)),
    (Scopes::Country, "ordered_fort_in_country", Scope(Scopes::Location)),
    (Scopes::Location, "ordered_friendly_coast_border_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_friendly_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_friendly_or_high_opinion_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_friendly_to_friendly_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_friendly_to_hostile_country", Scope(Scopes::Country)),
    (Scopes::Religion, "ordered_god_in_religion", Scope(Scopes::God)),
    (Scopes::Demand, "ordered_good_in_demand", Scope(Scopes::Goods)),
    (Scopes::None, "ordered_goods", Scope(Scopes::Goods)),
    (Scopes::Culture, "ordered_graphical_culture_in_culture", Scope(Scopes::GraphicalCulture)),
    (Scopes::None, "ordered_great_power", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_heathen_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_heretic_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_hired_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::Country, "ordered_historical_enemy", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_historical_rival", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_holy_site_in_country", Scope(Scopes::HolySite)),
    (Scopes::Religion, "ordered_holy_site_in_religion", Scope(Scopes::HolySite)),
    (Scopes::Country, "ordered_hostile_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_hostile_or_low_opinion_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_hostile_to_friendly_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_hostile_to_hostile_country", Scope(Scopes::Country)),
    (Scopes::Market, "ordered_import", Scope(Scopes::Trade)),
    (Scopes::Location, "ordered_import_from_location", Scope(Scopes::Location)),
    (Scopes::None, "ordered_in_global_list", UncheckedTodo),
    (Scopes::None, "ordered_in_list", UncheckedTodo),
    (Scopes::None, "ordered_in_local_list", UncheckedTodo),
    (Scopes::Country, "ordered_institutions_embraced", Scope(Scopes::Institution)),
    (Scopes::None, "ordered_international_organization", Scope(Scopes::InternationalOrganization)),
    (
        Scopes::InternationalOrganization,
        "ordered_international_organization_elector",
        Scope(Scopes::Country),
    ),
    (
        Scopes::InternationalOrganization,
        "ordered_international_organization_enemy",
        Scope(Scopes::Country),
    ),
    (
        Scopes::InternationalOrganization,
        "ordered_international_organization_member",
        Scope(Scopes::Country),
    ),
    (
        Scopes::InternationalOrganization,
        "ordered_international_organization_owned_location",
        Scope(Scopes::Location),
    ),
    (
        Scopes::Location,
        "ordered_international_organization_owner",
        Scope(Scopes::InternationalOrganization),
    ),
    (
        Scopes::InternationalOrganization,
        "ordered_international_organization_parliament_opposers",
        Scope(Scopes::Country),
    ),
    (
        Scopes::InternationalOrganization,
        "ordered_international_organization_parliament_supporter",
        Scope(Scopes::Country),
    ),
    (
        Scopes::Country,
        "ordered_international_organizations_member_of",
        Scope(Scopes::InternationalOrganization),
    ),
    (
        Scopes::Country,
        "ordered_international_organizations_target_of",
        Scope(Scopes::InternationalOrganization),
    ),
    (Scopes::Country, "ordered_invited_religious_figure", Scope(Scopes::Character)),
    (Scopes::Country, "ordered_known_country", Scope(Scopes::Country)),
    (Scopes::CombatSide, "ordered_left_flank", Scope(Scopes::SubUnit)),
    (Scopes::Country, "ordered_lent_loan", Scope(Scopes::Loan)),
    (Scopes::Country, "ordered_loan", Scope(Scopes::Loan)),
    (Scopes::Country, "ordered_loan_lent_to_country", Scope(Scopes::Loan)),
    (Scopes::Area, "ordered_location_in_area", Scope(Scopes::Location)),
    (Scopes::Continent, "ordered_location_in_continent", Scope(Scopes::Location)),
    (Scopes::Market, "ordered_location_in_market", Scope(Scopes::Location)),
    (Scopes::Province, "ordered_location_in_province", Scope(Scopes::Location)),
    (
        Scopes::ProvinceDefinition,
        "ordered_location_in_province_definition",
        Scope(Scopes::Location),
    ),
    (Scopes::Region, "ordered_location_in_region", Scope(Scopes::Location)),
    (Scopes::SubContinent, "ordered_location_in_sub_continent", Scope(Scopes::Location)),
    (Scopes::None, "ordered_location_in_the_world", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_loyal_subject", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_maritime_area", Scope(Scopes::Area)),
    (Scopes::Country, "ordered_market_center_in_country", Scope(Scopes::Market)),
    (Scopes::None, "ordered_market_in_world", Scope(Scopes::Market)),
    (Scopes::Country, "ordered_market_present_in_country", Scope(Scopes::Market)),
    (Scopes::Country, "ordered_market_with_merchants", Scope(Scopes::Market)),
    (Scopes::None, "ordered_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::Mercenary, "ordered_mercenary_sub_unit", Scope(Scopes::SubUnit)),
    (Scopes::Market, "ordered_merchant_in_market", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_navy", Scope(Scopes::Unit)),
    (Scopes::Area, "ordered_neighbor_area", Scope(Scopes::Area)),
    (Scopes::Country, "ordered_neighbor_country", Scope(Scopes::Country)),
    (Scopes::Location, "ordered_neighbor_location", Scope(Scopes::Location)),
    (
        Scopes::ProvinceDefinition,
        "ordered_neighbor_province_definition",
        Scope(Scopes::ProvinceDefinition),
    ),
    (Scopes::Location, "ordered_nomad_countries_in_location", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_non_state_religion_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_other_core_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_other_country", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_other_great_power", Scope(Scopes::Country)),
    (Scopes::Religion, "ordered_other_religion_in_same_group", Scope(Scopes::Religion)),
    (Scopes::Country, "ordered_other_revolutionary", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_overlord_or_above", Scope(Scopes::Country)),
    (Scopes::None, "ordered_ownable_location", Scope(Scopes::Location)),
    (Scopes::Area, "ordered_ownable_location_in_area", Scope(Scopes::Location)),
    (Scopes::Continent, "ordered_ownable_location_in_continent", Scope(Scopes::Location)),
    (
        Scopes::ProvinceDefinition,
        "ordered_ownable_location_in_province_definition",
        Scope(Scopes::Location),
    ),
    (Scopes::Region, "ordered_ownable_location_in_region", Scope(Scopes::Location)),
    (Scopes::SubContinent, "ordered_ownable_location_in_sub_continent", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_owned_building", Scope(Scopes::Building)),
    (Scopes::Country, "ordered_owned_foreign_building", Scope(Scopes::Building)),
    (Scopes::Country, "ordered_owned_foreign_building_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_owned_foreign_building_region", Scope(Scopes::Region)),
    (Scopes::Country, "ordered_owned_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_owned_nomad_pop", Scope(Scopes::Pop)),
    (Scopes::Country, "ordered_owned_non_rural_location", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_owned_rural_location", Scope(Scopes::Location)),
    (Scopes::Region, "ordered_owner_in_region", Scope(Scopes::Country)),
    (Scopes::Character, "ordered_parent", Scope(Scopes::Character)),
    (Scopes::CombatSide, "ordered_participating_countries", Scope(Scopes::Country)),
    (Scopes::CombatSide, "ordered_participating_units", Scope(Scopes::Unit)),
    (Scopes::Country, "ordered_past_liturgical_dialect", Scope(Scopes::Country)),
    (Scopes::Law, "ordered_policy_in_law", Scope(Scopes::Policy)),
    (Scopes::Country, "ordered_political_border_location", Scope(Scopes::Location)),
    (Scopes::Location.union(Scopes::Country), "ordered_pop", Scope(Scopes::Pop)),
    (Scopes::Rebels, "ordered_pops_supporting_rebel", Scope(Scopes::Pop)),
    (Scopes::Country, "ordered_port_in_country", Scope(Scopes::Location)),
    (Scopes::Country, "ordered_possible_disaster", Scope(Scopes::Disaster)),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "ordered_possible_parliament_issue",
        Scope(Scopes::ParliamentIssue),
    ),
    (Scopes::Country, "ordered_possible_policy", Scope(Scopes::Policy)),
    (Scopes::Estate, "ordered_possible_privilege", Scope(Scopes::EstatePrivilege)),
    (Scopes::Country, "ordered_possible_recruit_location", Scope(Scopes::Location)),
    (
        Scopes::Location
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Area)
            .union(Scopes::Region)
            .union(Scopes::SubContinent)
            .union(Scopes::Continent),
        "ordered_present_country",
        Scope(Scopes::Country),
    ),
    (Scopes::Country, "ordered_present_culture_in_country", Scope(Scopes::Culture)),
    (Scopes::Location, "ordered_present_culture_in_location", Scope(Scopes::Culture)),
    (
        Scopes::Location
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Area)
            .union(Scopes::Region)
            .union(Scopes::SubContinent)
            .union(Scopes::Continent),
        "ordered_present_overlord",
        Scope(Scopes::Country),
    ),
    (Scopes::Country, "ordered_present_religion_in_country", Scope(Scopes::Religion)),
    (Scopes::Location, "ordered_present_religion_in_location", Scope(Scopes::Religion)),
    (Scopes::Country, "ordered_primary_or_accepted_culture", Scope(Scopes::Culture)),
    (Scopes::Country, "ordered_primary_or_accepted_or_tolerated_culture", Scope(Scopes::Culture)),
    (Scopes::None, "ordered_privateer", Scope(Scopes::Privateer)),
    (Scopes::Country, "ordered_privateer_from_country", Scope(Scopes::Privateer)),
    (Scopes::Area, "ordered_privateer_in_area", Scope(Scopes::Privateer)),
    (Scopes::None, "ordered_production_method", Scope(Scopes::ProductionMethod)),
    (Scopes::Building, "ordered_production_method_of_building", Scope(Scopes::ProductionMethod)),
    (Scopes::Country, "ordered_province", Scope(Scopes::Province)),
    (Scopes::None, "ordered_province_definition", Scope(Scopes::ProvinceDefinition)),
    (Scopes::Area, "ordered_province_definition_in_area", Scope(Scopes::ProvinceDefinition)),
    (Scopes::Area, "ordered_province_in_area", Scope(Scopes::Province)),
    (
        Scopes::ProvinceDefinition,
        "ordered_province_in_province_definition",
        Scope(Scopes::Province),
    ),
    (Scopes::Country, "ordered_rebel", Scope(Scopes::Rebels)),
    (Scopes::None, "ordered_region", Scope(Scopes::Region)),
    (Scopes::SubContinent, "ordered_region_in_continent", Scope(Scopes::Region)),
    (Scopes::Country, "ordered_related_country", Scope(Scopes::Country)),
    (Scopes::None, "ordered_religion", Scope(Scopes::Religion)),
    (Scopes::God, "ordered_religion_for_god", Scope(Scopes::Religion)),
    (Scopes::Group, "ordered_religion_in_religion_group", Scope(Scopes::Religion)),
    (
        Scopes::Religion,
        "ordered_religion_international_organization",
        Scope(Scopes::InternationalOrganization),
    ),
    (Scopes::Country, "ordered_religious_aspect", Scope(Scopes::ReligiousAspect)),
    (Scopes::Country, "ordered_religious_focus", Scope(Scopes::ReligiousFocus)),
    (Scopes::Country, "ordered_rented_out_mercenary", Scope(Scopes::Mercenary)),
    (Scopes::ProductionMethod, "ordered_required_goods", Scope(Scopes::Goods)),
    (Scopes::CombatSide, "ordered_reserves", Scope(Scopes::SubUnit)),
    (Scopes::CombatSide, "ordered_retreated", Scope(Scopes::SubUnit)),
    (Scopes::None, "ordered_revolutionary", Scope(Scopes::Country)),
    (Scopes::CombatSide, "ordered_right_flank", Scope(Scopes::SubUnit)),
    (Scopes::Country, "ordered_rival", Scope(Scopes::Country)),
    (Scopes::None, "ordered_road_type", Scope(Scopes::RoadType)),
    (Scopes::Country, "ordered_royal_marriage", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_ruler", Scope(Scopes::Character)),
    (Scopes::Character, "ordered_ruling_countries", Scope(Scopes::Country)),
    (Scopes::Character, "ordered_spouse", Scope(Scopes::Character)),
    (Scopes::Country, "ordered_spy_network_built_in_us", Scope(Scopes::Country)),
    (Scopes::None, "ordered_sub_continent", Scope(Scopes::SubContinent)),
    (Scopes::Continent, "ordered_sub_continent_in_continent", Scope(Scopes::SubContinent)),
    (Scopes::Unit, "ordered_sub_unit", Scope(Scopes::SubUnit)),
    (Scopes::Country, "ordered_subject", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_subject_or_below", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_tolerated_culture", Scope(Scopes::Culture)),
    (Scopes::Country, "ordered_trade", Scope(Scopes::Trade)),
    (Scopes::Country, "ordered_union_partner", Scope(Scopes::Country)),
    (Scopes::Country, "ordered_unit", Scope(Scopes::Unit)),
    (Scopes::Location, "ordered_unit_in_location", Scope(Scopes::Unit)),
    (Scopes::ReligiousAspect, "ordered_valid_religion_for_aspect", Scope(Scopes::Religion)),
    (Scopes::ActiveResolution, "ordered_voter", Scope(Scopes::Country)),
    (Scopes::None, "ordered_war", Scope(Scopes::War)),
    (Scopes::War, "ordered_war_participant", Scope(Scopes::Country)),
    (Scopes::Location, "ordered_weather_system_in_location", Scope(Scopes::WeatherSystem)),
    (
        Scopes::ProvinceDefinition,
        "ordered_west_of_province_definition",
        Scope(Scopes::ProvinceDefinition),
    ),
    (Scopes::None, "ordered_work_of_art", Scope(Scopes::WorkOfArt)),
    (Scopes::Character, "ordered_work_of_art_by_creator", Scope(Scopes::WorkOfArt)),
    (Scopes::Country, "ordered_work_of_art_in_country", Scope(Scopes::WorkOfArt)),
    (Scopes::Location, "ordered_work_of_art_in_location", Scope(Scopes::WorkOfArt)),
    (Scopes::Country, "pay_off_loans", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "pay_policy_price_effect",
        Scope(Scopes::Policy),
    ),
    (Scopes::Country, "pay_price", Scope(Scopes::Price)),
    (Scopes::Country, "perform_diplomatic_action", UncheckedTodo),
    (Scopes::None, "post_audio_event", UncheckedTodo),
    (Scopes::None, "propose_resolution", UncheckedTodo),
    (Scopes::Country, "raise_all_levies", UncheckedTodo),
    (Scopes::Province, "raise_levies", UncheckedTodo),
    (Scopes::None, "random", UncheckedTodo),
    (Scopes::None, "random_list", UncheckedTodo),
    (Scopes::None, "random_log_scopes", UncheckedTodo),
    (Scopes::Unit, "ransom_prisoners", UncheckedTodo),
    (Scopes::None, "refresh_map_colors", UncheckedTodo),
    (Scopes::Country, "refund_price", Scope(Scopes::Price)),
    (Scopes::Country, "release_non_cores", UncheckedTodo),
    (Scopes::Market, "relocate_market", Scope(Scopes::Location)),
    (Scopes::Country, "remove_accepted_culture", Scope(Scopes::Culture)),
    (Scopes::ColonialCharter, "remove_additional_migration", UncheckedTodo),
    (Scopes::Country, "remove_all_casus_belli", Scope(Scopes::Country)),
    (Scopes::Country, "remove_antagonism", UncheckedTodo),
    (Scopes::Country, "remove_avatar", Scope(Scopes::Avatar)),
    (Scopes::Siege, "remove_breach", UncheckedTodo),
    (Scopes::Country, "remove_casus_belli", UncheckedTodo),
    (Scopes::Character, "remove_character_allegiance", UncheckedTodo),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_character_modifier",
        UncheckedTodo,
    ),
    (Scopes::None, "remove_colonial_claim", Scope(Scopes::ProvinceDefinition)),
    (Scopes::None, "remove_commander", Scope(Scopes::Character)),
    (Scopes::Country.union(Scopes::InternationalOrganization), "remove_cooldown", UncheckedTodo),
    (Scopes::Location, "remove_core", Scope(Scopes::Country)),
    (
        Scopes::InternationalOrganization,
        "remove_country_from_international_organization",
        Scope(Scopes::Country),
    ),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_country_modifier",
        UncheckedTodo,
    ),
    (
        Scopes::InternationalOrganization,
        "remove_enemy_from_international_organization",
        Scope(Scopes::Country),
    ),
    (Scopes::None, "remove_extended_winter", Scope(Scopes::Area)),
    (Scopes::Country, "remove_from_cabinet", Scope(Scopes::Character)),
    (
        Scopes::Location,
        "remove_from_international_organization",
        Scope(Scopes::InternationalOrganization),
    ),
    (Scopes::None, "remove_from_list", UncheckedTodo),
    (Scopes::None, "remove_global_variable", UncheckedTodo),
    (Scopes::Country, "remove_god", Scope(Scopes::God)),
    (Scopes::Country, "remove_historical_rival", Scope(Scopes::Country)),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_international_organization_modifier",
        UncheckedTodo,
    ),
    (Scopes::Country, "remove_law", Scope(Scopes::Law)),
    (
        Scopes::InternationalOrganization,
        "remove_law_from_international_organization",
        Scope(Scopes::Law),
    ),
    (Scopes::None, "remove_list_global_variable", UncheckedTodo),
    (Scopes::None, "remove_list_local_variable", UncheckedTodo),
    (Scopes::None, "remove_list_variable", UncheckedTodo),
    (Scopes::None, "remove_local_variable", UncheckedTodo),
    (
        Scopes::InternationalOrganization,
        "remove_location_from_international_organization",
        Scope(Scopes::Location),
    ),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_location_modifier",
        UncheckedTodo,
    ),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_mercenary_modifier",
        UncheckedTodo,
    ),
    (Scopes::Market, "remove_merchant_power", UncheckedTodo),
    (Scopes::None, "remove_migration", UncheckedTodo),
    (Scopes::Country, "remove_opinion", UncheckedTodo),
    (Scopes::Country, "remove_policy", Scope(Scopes::Policy)),
    (
        Scopes::InternationalOrganization,
        "remove_policy_from_international_organization",
        Scope(Scopes::Policy),
    ),
    (Scopes::Pop, "remove_pop_allegiance", UncheckedTodo),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_province_modifier",
        UncheckedTodo,
    ),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_rebel_modifier",
        UncheckedTodo,
    ),
    (Scopes::Country, "remove_reform", Scope(Scopes::GovernmentReform)),
    (Scopes::None, "remove_relation", UncheckedTodo),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_religion_modifier",
        UncheckedTodo,
    ),
    (Scopes::Country, "remove_religious_aspect", Scope(Scopes::ReligiousAspect)),
    (Scopes::Country, "remove_religious_focus", Scope(Scopes::ReligiousFocus)),
    (Scopes::Country, "remove_rival", Scope(Scopes::Country)),
    (Scopes::Character, "remove_ruler", Scope(Scopes::Country)),
    (Scopes::Market, "remove_temporary_demand", Scope(Scopes::Demand)),
    (Scopes::Country, "remove_tolerated_culture", Scope(Scopes::Culture)),
    (Scopes::Character, "remove_trait", Scope(Scopes::Trait)),
    (Scopes::Character, "remove_traits_of_category", UncheckedTodo),
    (Scopes::Country, "remove_truce_with", Scope(Scopes::Country)),
    (Scopes::Country, "remove_trust", UncheckedTodo),
    (
        Scopes::Location
            .union(Scopes::Country)
            .union(Scopes::Unit)
            .union(Scopes::Character)
            .union(Scopes::Religion)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary)
            .union(Scopes::InternationalOrganization),
        "remove_unit_modifier",
        UncheckedTodo,
    ),
    (Scopes::None, "remove_variable", UncheckedTodo),
    (Scopes::Location, "remove_vfx", UncheckedTodo),
    (Scopes::InternationalOrganization.union(Scopes::Situation), "remove_vote", UncheckedTodo),
    (Scopes::Location, "rename_location", UncheckedTodo),
    (Scopes::Unit, "request_ransom_prisoners", UncheckedTodo),
    (Scopes::Country, "research_advance", Scope(Scopes::AdvanceType)),
    (Scopes::Country, "reset_regency", UncheckedTodo),
    (Scopes::Country, "reverse_add_antagonism", UncheckedTodo),
    (Scopes::Country, "reverse_add_opinion", UncheckedTodo),
    (Scopes::Country, "reverse_add_trust", UncheckedTodo),
    (Scopes::Culture, "reverse_change_cultural_view", UncheckedTodo),
    (Scopes::Religion, "reverse_change_religion_view", UncheckedTodo),
    (Scopes::Culture, "reverse_set_cultural_view", UncheckedTodo),
    (Scopes::Religion, "reverse_set_religious_view", UncheckedTodo),
    (Scopes::ReligiousSchool, "reverse_set_school_opinion", UncheckedTodo),
    (Scopes::Country, "revoke_estate_privilege", Scope(Scopes::EstatePrivilege)),
    (Scopes::None, "round_global_variable", UncheckedTodo),
    (Scopes::None, "round_local_variable", UncheckedTodo),
    (Scopes::None, "round_variable", UncheckedTodo),
    (Scopes::None, "save_scope_as", UncheckedTodo),
    (Scopes::None, "save_scope_value_as", UncheckedTodo),
    (Scopes::None, "save_temporary_scope_as", UncheckedTodo),
    (Scopes::None, "save_temporary_scope_value_as", UncheckedTodo),
    (Scopes::Market, "sell_goods_from_location", UncheckedTodo),
    (Scopes::Unit, "sell_prisoners_into_slavery", UncheckedTodo),
    (Scopes::Country, "set_age_preference", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_army_tradition", UncheckedTodo),
    (Scopes::WorkOfArt, "set_art_owner", Scope(Scopes::Country)),
    (Scopes::Unit, "set_as_commander", Scope(Scopes::Character)),
    (Scopes::Country, "set_as_designated_heir", Scope(Scopes::Character)),
    (Scopes::Country, "set_automated_system", UncheckedTodo),
    (Scopes::Country, "set_bankruptcy", UncheckedTodo),
    (Scopes::Country, "set_capital", Scope(Scopes::Location)),
    (Scopes::Character, "set_child_education", Scope(Scopes::ChildEducation)),
    (Scopes::None, "set_collection_pin", UncheckedTodo),
    (Scopes::Country, "set_country_employment_system", Scope(Scopes::EmploymentSystem)),
    (Scopes::None, "set_country_military_stance", Scope(Scopes::MilitaryStance)),
    (Scopes::Country, "set_country_rank", Scope(Scopes::CountryRank)),
    (Scopes::Country, "set_court_language", Scope(Scopes::Dialect)),
    (Scopes::Culture, "set_cultural_view", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_devotion", UncheckedTodo),
    (Scopes::Location.union(Scopes::SubUnit), "set_disease_presence", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_doom", UncheckedTodo),
    (Scopes::Dynasty, "set_dynasty_name_type", UncheckedTodo),
    (Scopes::Character, "set_ethnicity", Scope(Scopes::Ethnicity)),
    (Scopes::Character, "set_first_name", UncheckedTodo),
    (Scopes::Location, "set_garrison_size", UncheckedTodo),
    (Scopes::None, "set_global_variable", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_gold", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_government_power",
        UncheckedTodo,
    ),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_harmony", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_honor", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_horde_unity", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_inflation", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_karma", UncheckedTodo),
    (Scopes::InternationalOrganization, "set_leader_country", Scope(Scopes::Country)),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_legitimacy", UncheckedTodo),
    (Scopes::Country, "set_liturgical_language", Scope(Scopes::Dialect)),
    (Scopes::Loan, "set_loc_key", UncheckedTodo),
    (Scopes::None, "set_local_variable", UncheckedTodo),
    (Scopes::Trade, "set_locked", UncheckedTodo),
    (Scopes::Character, "set_lowborn", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_manpower", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_navy_tradition", UncheckedTodo),
    (Scopes::Religion, "set_needs_reform", UncheckedTodo),
    (Scopes::Country, "set_new_foreign_ruler", Scope(Scopes::Character)),
    (Scopes::Country, "set_new_foreign_ruler_no_update", Scope(Scopes::Character)),
    (Scopes::Country, "set_new_ruler", Scope(Scopes::Character)),
    (Scopes::Country, "set_new_ruler_no_update", Scope(Scopes::Character)),
    (Scopes::Character, "set_nickname", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_parliament_active",
        UncheckedTodo,
    ),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_parliament_issue",
        Scope(Scopes::ParliamentIssue),
    ),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_parliament_issue_support",
        UncheckedTodo,
    ),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_parliament_location",
        Scope(Scopes::Location),
    ),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_parliament_type",
        Scope(Scopes::ParliamentType),
    ),
    (Scopes::Country, "set_participated_in_parliament", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_prestige", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_purity", UncheckedTodo),
    (Scopes::Country, "set_regent", Scope(Scopes::Character)),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_religious_influence",
        UncheckedTodo,
    ),
    (Scopes::Country, "set_religious_school", Scope(Scopes::ReligiousSchool)),
    (Scopes::Religion, "set_religious_view", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_republican_tradition",
        UncheckedTodo,
    ),
    (Scopes::Country, "set_revolution", UncheckedTodo),
    (Scopes::Country, "set_revolution_target", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_righteousness", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_rite_power", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_sailors", UncheckedTodo),
    (Scopes::ReligiousSchool, "set_school_opinion", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_self_control", UncheckedTodo),
    (Scopes::Country, "set_societal_value", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_stability", UncheckedTodo),
    (Scopes::Building, "set_subsidized", UncheckedTodo),
    (
        Scopes::InternationalOrganization,
        "set_target_of_international_organization",
        Scope(Scopes::Country),
    ),
    (Scopes::Character, "set_to_limited_random_stat", UncheckedTodo),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "set_tribal_cohesion",
        UncheckedTodo,
    ),
    (Scopes::None, "set_tutorial_var", UncheckedTodo),
    (Scopes::Unit, "set_unit_size", UncheckedTodo),
    (Scopes::None, "set_variable", UncheckedTodo),
    (Scopes::InternationalOrganization.union(Scopes::Situation), "set_vote", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_war_exhaustion", UncheckedTodo),
    (Scopes::Country.union(Scopes::InternationalOrganization), "set_yanantin", UncheckedTodo),
    (Scopes::None, "show_as_tooltip", UncheckedTodo),
    (Scopes::None, "sort_global_variable_list", UncheckedTodo),
    (Scopes::None, "sort_local_variable_list", UncheckedTodo),
    (Scopes::None, "sort_variable_list", UncheckedTodo),
    (Scopes::None, "spawn_army_levy_unit", Scope(Scopes::Country)),
    (Scopes::Location, "spawn_disease", Scope(Scopes::DiseaseOutbreak)),
    (Scopes::None, "spawn_navy_levy_unit", Scope(Scopes::Country)),
    (Scopes::Pop, "split_pop", UncheckedTodo),
    (Scopes::Exploration, "stall_exploration", UncheckedTodo),
    (Scopes::Rebels, "start_civil_war", Scope(Scopes::Country)),
    (Scopes::Country, "start_conquistador", UncheckedTodo),
    (Scopes::Country, "start_exploration", UncheckedTodo),
    (Scopes::Country, "start_mission", UncheckedTodo),
    (Scopes::WorkOfArt, "start_periphora_towards", Scope(Scopes::Location)),
    (Scopes::Rebels, "start_revolt", UncheckedTodo),
    (Scopes::None, "start_tutorial_lesson", UncheckedTodo),
    (Scopes::None, "start_weather_system", Scope(Scopes::WeatherSystem)),
    (Scopes::Character, "start_work_of_art", UncheckedTodo),
    (Scopes::Country, "stop_annexing_country", Scope(Scopes::Country)),
    (Scopes::Cabinet, "stop_cabinet_action", UncheckedTodo),
    (Scopes::None, "stop_tutorial", UncheckedTodo),
    (Scopes::Country, "support_rebel", Scope(Scopes::Rebels)),
    (Scopes::None, "switch", UncheckedTodo),
    (Scopes::Country, "take_over_all_wars", Scope(Scopes::Country)),
    (Scopes::None, "test_log", UncheckedTodo),
    (Scopes::Country, "transfer_yearly_gold", UncheckedTodo),
    (Scopes::Country, "transfer_yearly_manpower", UncheckedTodo),
    (Scopes::Country, "transfer_yearly_sailors", UncheckedTodo),
    (Scopes::None, "trigger_event_non_silently", UncheckedTodo),
    (Scopes::None, "trigger_event_silently", UncheckedTodo),
    (Scopes::Unit, "unlock_unit", UncheckedTodo),
    (Scopes::Country, "unset_participated_in_parliament", Scope(Scopes::InternationalOrganization)),
    (Scopes::None, "update_leadership", Scope(Scopes::InternationalOrganization)),
    (Scopes::None, "while", UncheckedTodo),
    (Scopes::None, "white_peace", Scope(Scopes::War)),
];
