#![allow(unused_imports)] // TODO EU5: remove this when ready
use std::sync::LazyLock;

use crate::helpers::TigerHashMap;
use crate::scopes::{ArgumentValue, Scopes};

#[inline]
pub fn scope_to_scope(name: &str) -> Option<(Scopes, Scopes)> {
    SCOPE_TO_SCOPE_MAP.get(name).copied()
}

static SCOPE_TO_SCOPE_MAP: LazyLock<TigerHashMap<&'static str, (Scopes, Scopes)>> =
    LazyLock::new(|| {
        let mut hash = TigerHashMap::default();
        for (from, s, to) in SCOPE_TO_SCOPE.iter().copied() {
            hash.insert(s, (from, to));
        }
        hash
    });

/// See `event_targets.log` from the game data dumps
/// These are scope transitions that can be chained like `root.joined_faction.faction_leader`
const SCOPE_TO_SCOPE: &[(Scopes, &str, Scopes)] = &[
    // TODO: EU5 verify the autogenerated table
    (Scopes::Country, "active_mission", Scopes::Mission),
    (
        Scopes::Location
            .union(Scopes::Province)
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Privateer)
            .union(Scopes::Exploration),
        "area",
        Scopes::Area,
    ),
    (Scopes::War, "attacker_leader", Scopes::Country),
    (Scopes::Country, "autocephalous_patriarchate", Scopes::InternationalOrganization),
    (Scopes::HolySite, "avatar", Scopes::Avatar),
    (Scopes::Character, "birth_location", Scopes::Location),
    (Scopes::Loan, "borrower", Scopes::Country),
    (Scopes::BuildingType, "building_base_cost_in_gold", Scopes::Value),
    (Scopes::Building, "building_type", Scopes::BuildingType),
    (Scopes::Character.union(Scopes::Cabinet), "cabinet_action", Scopes::CabinetAction),
    (Scopes::Cabinet, "cabinet_member", Scopes::Character),
    (Scopes::Trade, "capacity_market", Scopes::Market),
    (
        Scopes::Country.union(Scopes::Dynasty).union(Scopes::Province).union(Scopes::Area),
        "capital",
        Scopes::Location,
    ),
    (Scopes::Location, "cardinal", Scopes::Cardinal),
    (Scopes::War, "casus_belli", Scopes::CasusBelli),
    (Scopes::Country, "civil_war", Scopes::War),
    (Scopes::Country, "civil_war_opponent", Scopes::Country),
    (Scopes::Location.union(Scopes::Unit).union(Scopes::CombatSide), "combat", Scopes::Combat),
    (Scopes::Combat, "combat_attacker", Scopes::CombatSide),
    (Scopes::Combat, "combat_defender", Scopes::CombatSide),
    (Scopes::CombatSide, "commander", Scopes::Country),
    (Scopes::CombatSide, "commanding_country", Scopes::Country),
    (Scopes::Country, "consort", Scopes::Character),
    (
        Scopes::Location
            .union(Scopes::Province)
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Area)
            .union(Scopes::Region)
            .union(Scopes::SubContinent),
        "continent",
        Scopes::Continent,
    ),
    (Scopes::Location.union(Scopes::SubUnit), "controller", Scopes::Country),
    (Scopes::Country, "country_color", Scopes::Color),
    (Scopes::Country, "country_rank", Scopes::CountryRank),
    (Scopes::Country, "country_stance", Scopes::MilitaryStance),
    (Scopes::Country, "court_dialect", Scopes::Dialect),
    (Scopes::Country, "court_language", Scopes::Language),
    (Scopes::WorkOfArt, "creator", Scopes::Character),
    (
        Scopes::Country
            .union(Scopes::SubUnit)
            .union(Scopes::Character)
            .union(Scopes::Dynasty)
            .union(Scopes::Pop)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary),
        "culture",
        Scopes::Culture,
    ),
    (Scopes::Country, "current_mission_task", Scopes::MissionTask),
    (Scopes::Mercenary, "customer", Scopes::Country),
    (Scopes::War, "defender_leader", Scopes::Country),
    (
        Scopes::Character
            .union(Scopes::Dynasty)
            .union(Scopes::Pop)
            .union(Scopes::Culture)
            .union(Scopes::Religion)
            .union(Scopes::Market),
        "dialect",
        Scopes::Dialect,
    ),
    (Scopes::Disaster, "disaster_type", Scopes::DisasterType),
    (Scopes::DiseaseOutbreak, "disease", Scopes::Disease),
    (Scopes::Culture, "dominant_country", Scopes::Country),
    (
        Scopes::Location.union(Scopes::Country).union(Scopes::Province),
        "dominant_culture",
        Scopes::Culture,
    ),
    (Scopes::Location.union(Scopes::Country), "dominant_dialect", Scopes::Dialect),
    (Scopes::Location.union(Scopes::Country), "dominant_language", Scopes::Language),
    (
        Scopes::Location.union(Scopes::Country).union(Scopes::Province),
        "dominant_religion",
        Scopes::Religion,
    ),
    (Scopes::Country, "dominant_upper_class_culture", Scopes::Culture),
    (Scopes::Character, "dynasty", Scopes::Dynasty),
    (Scopes::Dynasty, "dynasty_head", Scopes::Character),
    (Scopes::Dynasty, "dynasty_home", Scopes::Location),
    (Scopes::Character, "employer", Scopes::Country),
    (Scopes::CombatSide, "enemy_side", Scopes::CombatSide),
    (Scopes::Estate, "estate_tax_base", Scopes::Value),
    (
        Scopes::Character
            .union(Scopes::Pop)
            .union(Scopes::Rebels)
            .union(Scopes::Building)
            .union(Scopes::EstatePrivilege)
            .union(Scopes::ParliamentIssue)
            .union(Scopes::Estate),
        "estate_type",
        Scopes::EstateType,
    ),
    (Scopes::Character, "ethnicity", Scopes::Ethnicity),
    (Scopes::Character, "exploration", Scopes::Exploration),
    (Scopes::Character, "father", Scopes::Character),
    (Scopes::Character, "first_spouse", Scopes::Character),
    (Scopes::Trade, "from_market", Scopes::Market),
    (Scopes::Culture, "gfx_culture", Scopes::GraphicalCulture),
    (Scopes::HolySite.union(Scopes::Avatar), "god", Scopes::God),
    (Scopes::Country, "government_type", Scopes::Government),
    (Scopes::Religion, "group", Scopes::Group),
    (Scopes::Country, "heir", Scopes::Character),
    (Scopes::God.union(Scopes::Avatar), "holy_site", Scopes::HolySite),
    (Scopes::InternationalOrganization, "international_organization_target", Scopes::Country),
    (
        Scopes::InternationalOrganization,
        "international_organization_type",
        Scopes::InternationalOrganizationType,
    ),
    (Scopes::InternationalOrganization, "land_ownership_rule", Scopes::LandOwnershipRule),
    (
        Scopes::Country
            .union(Scopes::SubUnit)
            .union(Scopes::Character)
            .union(Scopes::Dynasty)
            .union(Scopes::Culture)
            .union(Scopes::Religion)
            .union(Scopes::Market)
            .union(Scopes::Dialect),
        "language",
        Scopes::Language,
    ),
    (Scopes::Language, "language_family", Scopes::LanguageFamily),
    (Scopes::Location, "last_dynasty_in_location", Scopes::Dynasty),
    (Scopes::InternationalOrganization, "last_leader_country", Scopes::Country),
    (Scopes::Country, "last_valid_ruler", Scopes::Character),
    (Scopes::Policy, "law", Scopes::Law),
    (Scopes::Unit.union(Scopes::Exploration), "leader", Scopes::Character),
    (Scopes::InternationalOrganization, "leader_country", Scopes::Country),
    (Scopes::InternationalOrganization, "leadership_election_resolution", Scopes::Resolution),
    (Scopes::CombatSide, "leading_unit", Scopes::Unit),
    (Scopes::Country, "liturgical_dialect", Scopes::Dialect),
    (Scopes::Country, "liturgical_language", Scopes::Language),
    (
        Scopes::Character
            .union(Scopes::Pop)
            .union(Scopes::Combat)
            .union(Scopes::Siege)
            .union(Scopes::Market)
            .union(Scopes::Exploration)
            .union(Scopes::WorkOfArt)
            .union(Scopes::HolySite)
            .union(Scopes::Building)
            .union(Scopes::Cardinal),
        "location",
        Scopes::Location,
    ),
    (Scopes::Location, "location_rank", Scopes::LocationRank),
    (Scopes::Country, "low_control_best_tax_base", Scopes::Province),
    (Scopes::Location, "market", Scopes::Market),
    (Scopes::Country, "marriage_union", Scopes::InternationalOrganization),
    (Scopes::Mercenary, "mercenary_home", Scopes::Location),
    (Scopes::Market, "most_powerful_merchant", Scopes::Country),
    (Scopes::Character, "mother", Scopes::Character),
    (Scopes::SubUnit, "name_culture", Scopes::Culture),
    (
        Scopes::WorkOfArt
            .union(Scopes::Institution)
            .union(Scopes::DiseaseOutbreak)
            .union(Scopes::Disease),
        "origin",
        Scopes::Location,
    ),
    (Scopes::Disease, "original_outbreak", Scopes::DiseaseOutbreak),
    (Scopes::Country, "overlord", Scopes::Country),
    (
        Scopes::Location
            .union(Scopes::Unit)
            .union(Scopes::SubUnit)
            .union(Scopes::Character)
            .union(Scopes::Pop)
            .union(Scopes::ColonialCharter)
            .union(Scopes::Market)
            .union(Scopes::Province)
            .union(Scopes::Rebels)
            .union(Scopes::Trade)
            .union(Scopes::Privateer)
            .union(Scopes::Exploration)
            .union(Scopes::Mercenary)
            .union(Scopes::WorkOfArt)
            .union(Scopes::Loan)
            .union(Scopes::Building)
            .union(Scopes::Disaster)
            .union(Scopes::Cabinet)
            .union(Scopes::Cardinal)
            .union(Scopes::Estate),
        "owner",
        Scopes::Country,
    ),
    (Scopes::SubUnit, "owning_unit", Scopes::Unit),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "parliament_issue",
        Scopes::ParliamentIssue,
    ),
    (Scopes::Country.union(Scopes::InternationalOrganization), "parliament_seat", Scopes::Location),
    (
        Scopes::Country.union(Scopes::InternationalOrganization),
        "parliament_type",
        Scopes::ParliamentType,
    ),
    (Scopes::Pop, "pop_type", Scopes::PopType),
    (Scopes::Location, "previous_owner", Scopes::Country),
    (Scopes::Country, "previous_ruler", Scopes::Character),
    (Scopes::Policy, "price", Scopes::Price),
    (Scopes::ProductionMethod, "produced_goods", Scopes::Goods),
    (Scopes::Location, "province", Scopes::Province),
    (Scopes::Province, "province_capital", Scopes::Location),
    (
        Scopes::Location.union(Scopes::ColonialCharter).union(Scopes::Province),
        "province_definition",
        Scopes::ProvinceDefinition,
    ),
    (Scopes::Location, "raw_material", Scopes::Goods),
    (Scopes::Location, "raw_material_location", Scopes::Goods),
    (Scopes::Character.union(Scopes::Pop), "rebel", Scopes::Rebels),
    (Scopes::Country, "regency_type", Scopes::RegencyType),
    (Scopes::Country, "regent", Scopes::Character),
    (
        Scopes::Location
            .union(Scopes::Province)
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Area),
        "region",
        Scopes::Region,
    ),
    (
        Scopes::Country
            .union(Scopes::SubUnit)
            .union(Scopes::Character)
            .union(Scopes::Dynasty)
            .union(Scopes::Pop)
            .union(Scopes::Rebels)
            .union(Scopes::Mercenary),
        "religion",
        Scopes::Religion,
    ),
    (Scopes::Religion, "religious_head", Scopes::Country),
    (Scopes::Country.union(Scopes::Character), "religious_school", Scopes::ReligiousSchool),
    (Scopes::ActiveResolution, "resolution", Scopes::Resolution),
    (Scopes::ActiveResolution, "resolution_proposer", Scopes::Country),
    (Scopes::Country, "ruler", Scopes::Character),
    (Scopes::Country, "ruler_or_heir_if_regent", Scopes::Character),
    (Scopes::Country, "ruler_or_regent", Scopes::Character),
    (Scopes::Location, "sea_zone", Scopes::Location),
    (Scopes::Location, "second_best_market", Scopes::Market),
    (Scopes::Location, "secondary_culture", Scopes::Culture),
    (Scopes::Location, "secondary_otherwise_primary_culture", Scopes::Culture),
    (Scopes::Location.union(Scopes::Unit), "siege", Scopes::Siege),
    (Scopes::Siege, "siege_defender", Scopes::Country),
    (Scopes::Siege, "siege_main_attacker", Scopes::Country),
    (Scopes::ColonialCharter, "source_province", Scopes::Province),
    (Scopes::ParliamentIssue, "special_status", Scopes::SpecialStatus),
    (
        Scopes::Location
            .union(Scopes::Province)
            .union(Scopes::ProvinceDefinition)
            .union(Scopes::Area)
            .union(Scopes::Region),
        "sub_continent",
        Scopes::SubContinent,
    ),
    (Scopes::SubUnit, "sub_unit_category", Scopes::SubUnitCategory),
    (Scopes::Country, "subject_type", Scopes::SubjectType),
    (Scopes::SubUnit, "subunit_home", Scopes::Location),
    (Scopes::Country, "succession_law", Scopes::HeirSelection),
    (Scopes::Trade, "to_market", Scopes::Market),
    (Scopes::Country, "top_overlord", Scopes::Country),
    (Scopes::Country, "top_overlord_or_this", Scopes::Country),
    (Scopes::Location, "top_owner", Scopes::Country),
    (Scopes::Trade, "traded_goods", Scopes::Goods),
    (Scopes::Country, "union", Scopes::InternationalOrganization),
    (Scopes::Character, "unit", Scopes::Unit),
    (Scopes::Unit, "unit_destination", Scopes::Location),
    (Scopes::Unit, "unit_location", Scopes::Location),
    (Scopes::Unit, "unit_next_location", Scopes::Location),
    (Scopes::ProductionMethod, "upgrade_demand", Scopes::Demand),
    (Scopes::WorkOfArt, "work_of_art_type", Scopes::WorkOfArtType),
];

#[inline]
pub fn scope_prefix(name: &str) -> Option<(Scopes, Scopes, ArgumentValue)> {
    SCOPE_PREFIX_MAP.get(name).copied()
}

static SCOPE_PREFIX_MAP: LazyLock<TigerHashMap<&'static str, (Scopes, Scopes, ArgumentValue)>> =
    LazyLock::new(|| {
        let mut hash = TigerHashMap::default();
        for (from, s, to, argument) in SCOPE_PREFIX.iter().copied() {
            hash.insert(s, (from, to, argument));
        }
        hash
    });

/// See `event_targets.log` from the game data dumps
/// These are absolute scopes (like character:100000) and scope transitions that require
/// a key (like `root.cp:councillor_steward`)
const SCOPE_PREFIX: &[(Scopes, &str, Scopes, ArgumentValue)] = {
    use crate::item::Item;
    use ArgumentValue::*;
    &[
        // TODO: EU5 fill in the UncheckedValue entries and the entries with Scopes::all() output scopes
        (
            Scopes::Location.union(Scopes::SubUnit),
            "active_outbreak",
            Scopes::DiseaseOutbreak,
            UncheckedValue,
        ),
        (
            Scopes::InternationalOrganization.union(Scopes::Situation),
            "active_resolution",
            Scopes::ActiveResolution,
            UncheckedValue,
        ),
        (Scopes::Area, "area_exploration", Scopes::Exploration, UncheckedValue),
        (Scopes::Location, "building", Scopes::Building, UncheckedValue),
        (Scopes::ActiveResolution, "cast_vote_in_active_resolution", Scopes::all(), UncheckedValue),
        (Scopes::Country, "country_rank_on_date", Scopes::CountryRank, UncheckedValue),
        (Scopes::Country, "estate", Scopes::Estate, UncheckedValue),
        (Scopes::Country, "estate_power", Scopes::Value, UncheckedValue),
        (Scopes::Country, "estate_satisfaction", Scopes::Value, UncheckedValue),
        (Scopes::Country, "estate_target_satisfaction", Scopes::Value, UncheckedValue),
        (Scopes::Country, "estate_tax_base", Scopes::Value, UncheckedValue),
        (Scopes::Country, "estate_tax_percentage", Scopes::Value, UncheckedValue),
        (Scopes::Location, "institution_progress", Scopes::Value, UncheckedValue),
        (Scopes::Cabinet, "interaction_target", Scopes::all(), UncheckedValue),
        (Scopes::Country, "known_in_country", Scopes::Value, UncheckedValue),
        (
            Scopes::Country.union(Scopes::InternationalOrganization),
            "law_policy",
            Scopes::Policy,
            UncheckedValue,
        ),
        (Scopes::InternationalOrganization, "leader_at_index", Scopes::Character, UncheckedValue),
        (Scopes::Market, "market_price", Scopes::Value, UncheckedValue),
        (
            Scopes::Location
                .union(Scopes::Country)
                .union(Scopes::Unit)
                .union(Scopes::Character)
                .union(Scopes::Religion)
                .union(Scopes::Province)
                .union(Scopes::InternationalOrganization),
            "modifier",
            Scopes::Value.union(Scopes::Bool),
            UncheckedValue,
        ),
        (Scopes::Country, "num_estate_privileges", Scopes::Value, UncheckedValue),
        (Scopes::Country, "num_location_rank", Scopes::Value, UncheckedValue),
        (Scopes::Location, "num_pop_type", Scopes::Value, UncheckedValue),
        (Scopes::Country, "num_pop_type_in_country", Scopes::Value, UncheckedValue),
        (Scopes::Province, "num_pop_type_in_province", Scopes::Value, UncheckedValue),
        (Scopes::Country, "num_possible_estate_privileges", Scopes::Value, UncheckedValue),
        (Scopes::Country, "percentage_pop_type_in_country", Scopes::Value, UncheckedValue),
        (Scopes::Location, "percentage_pop_type_in_location", Scopes::Value, UncheckedValue),
        (Scopes::Country, "produced_in_country", Scopes::Value, UncheckedValue),
        (Scopes::Market, "produced_in_market", Scopes::Value, UncheckedValue),
        (Scopes::Country, "province", Scopes::Province, UncheckedValue),
        (Scopes::ActiveResolution, "resolution_target", Scopes::all(), UncheckedValue),
        (Scopes::Character, "rule_end_date", Scopes::Date, UncheckedValue),
        (Scopes::Country, "societal_value", Scopes::Value, UncheckedValue),
        (Scopes::Market, "stockpile_in_market", Scopes::Value, UncheckedValue),
        (Scopes::Unit, "sub_unit_count", Scopes::Value, UncheckedValue),
        (Scopes::Unit, "sub_unit_fraction", Scopes::Value, UncheckedValue),
        (Scopes::Unit, "sub_unit_strength", Scopes::Value, UncheckedValue),
        (Scopes::Market, "target_price", Scopes::Value, UncheckedValue),
        (Scopes::Country, "total_effective_building_levels", Scopes::Value, UncheckedValue),
        (Scopes::Unit, "total_sub_unit_category_in_unit", Scopes::Value, UncheckedValue),
        (Scopes::Country, "total_sub_unit_count", Scopes::Value, UncheckedValue),
        (Scopes::Country, "total_sub_unit_strength", Scopes::Value, UncheckedValue),
        (Scopes::Country, "total_sub_unit_type_count", Scopes::Value, UncheckedValue),
        (Scopes::Unit, "total_sub_unit_type_strength", Scopes::Value, UncheckedValue),
        (Scopes::Market, "traded_in_market", Scopes::Value, UncheckedValue),
        (Scopes::ActiveResolution, "vote_in_active_resolution", Scopes::all(), UncheckedValue),
        (Scopes::Country, "war_with_country", Scopes::War, UncheckedValue),
    ]
};

pub fn scope_to_scope_removed(name: &str) -> Option<(&'static str, &'static str)> {
    for (removed_name, version, explanation) in SCOPE_TO_SCOPE_REMOVED.iter().copied() {
        if name == removed_name {
            return Some((version, explanation));
        }
    }
    None
}

const SCOPE_TO_SCOPE_REMOVED: &[(&str, &str, &str)] = &[];
