&[
    ("AIWatchWindowsEnabled", Args::Args(&[]), bool),
    ("AbandonPlayerRulerObjectiveDecision", Args::Args(&[]), Ck3(Command)),
    ("Abs_CFixedPoint", Args::Args(&[DType(CFixedPoint)]), CFixedPoint),
    ("Abs_float", Args::Args(&[DType(float)]), float),
    ("Abs_int32", Args::Args(&[DType(int32)]), int32),
    ("AccessLocalPlayerCachedData", Args::Args(&[]), Ck3(LocalPlayerCachedData)),
    ("AccessMapEditorLayerBorders", Args::Args(&[]), Unknown),
    ("AccessSuggestionItems", Args::Args(&[]), Unknown),
    ("AccessTopBar", Args::Args(&[]), Ck3(InGameTopbar)),
    ("AddLine", Args::Args(&[DType(CString)]), CString),
    ("AddLocalizationIf", Args::Args(&[DType(bool), DType(CString)]), CString),
    ("AddParagraph", Args::Args(&[DType(CString)]), CString),
    ("AddTextIf", Args::Args(&[DType(bool), DType(CString)]), CString),
    ("AddWatchWindow", Args::Args(&[DType(Scope)]), void),
    ("Add_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Add_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Add_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector3f),
    ("Add_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector4f),
    ("Add_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Add_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Add_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("And", Args::Args(&[DType(bool), DType(bool)]), bool),
    ("AreAchievementsAvailable", Args::Args(&[]), bool),
    ("BindFoldOutContext", Args::Args(&[]), void),
    ("BindTabsContext", Args::Args(&[]), void),
    ("BoolTo1And2", Args::Args(&[DType(bool)]), int32),
    ("BoolTo2And1", Args::Args(&[DType(bool)]), int32),
    ("CalcProgressBetweenDates", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), float),
    ("CalcResolutionLimitAspectRatio", Args::Args(&[]), CVector2f),
    ("CalculateBreakdownItems", Args::Args(&[DType(Ck3(Army))]), Unknown),
    ("CanAnyoneUnpause", Args::Args(&[]), bool),
    ("CanChangeMapMode", Args::Args(&[]), bool),
    ("CanDecreaseGameSpeed", Args::Args(&[]), bool),
    ("CanEditSettingsAfterHost", Args::Args(&[]), bool),
    ("CanGetAchievements", Args::Args(&[]), bool),
    ("CanIncreaseGameSpeed", Args::Args(&[]), bool),
    ("CanMakeLandlessCharacter", Args::Args(&[]), bool),
    ("CanMakeNobleFamilyCharacters", Args::Args(&[]), bool),
    ("CanOpenLobby", Args::Args(&[]), bool),
    ("ClearAdminVassalDetailCandidate", Args::Args(&[]), void),
    ("ClearErrorLog", Args::Args(&[]), void),
    ("ClearExploringHouses", Args::Args(&[]), void),
    ("ClearExploringRealms", Args::Args(&[]), void),
    ("ClearHighlightedStruggleBorder", Args::Args(&[]), void),
    ("ClearHostError", Args::Args(&[]), void),
    ("ClearObserver", Args::Args(&[]), void),
    ("ClearResetReactiveTutorialPopup", Args::Args(&[]), void),
    ("CloseAllTooltips", Args::Args(&[]), void),
    ("CloseGameView", Args::Args(&[DType(CString)]), void),
    ("ConcatIfNeitherEmpty", Args::Args(&[DType(CString), DType(CString)]), CString),
    ("Concatenate", Args::Args(&[DType(CString), DType(CString)]), CString),
    ("Concept", Args::Args(&[IType(Item::GameConcept), DType(CString)]), CString),
    ("ConceptByKey", Args::Args(&[IType(Item::GameConcept)]), CString),
    ("CopyBuildVersionInfoToClipboard", Args::Args(&[]), void),
    ("CopyServerID", Args::Args(&[]), void),
    ("CreateCommandPopup", Args::Args(&[DType(Ck3(Command))]), void),
    ("CurrentAndMaxToProgressbarValueInt32", Args::Args(&[DType(int32), DType(int32)]), float),
    ("DataModelFirst", Args::Args(&[DType(Unknown), DType(int32)]), Unknown),
    ("DataModelHasItems", Args::Args(&[DType(Unknown)]), bool),
    ("DataModelLast", Args::Args(&[DType(Unknown), DType(int32)]), Unknown),
    ("DataModelSkipFirst", Args::Args(&[DType(Unknown), DType(int32)]), Unknown),
    ("DataModelSkipLast", Args::Args(&[DType(Unknown), DType(int32)]), Unknown),
    ("DataModelSubSpan", Args::Args(&[DType(Unknown), DType(int32), DType(int32)]), Unknown),
    ("DaysPerMonth", Args::Args(&[]), int32),
    ("DaysPerWeek", Args::Args(&[]), int32),
    ("DaysPerYear", Args::Args(&[]), int32),
    ("DefaultOnBarterClick", Args::Args(&[DType(Ck3(BarterMission))]), void),
    ("DefaultOnCharacterClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnCharacterRightClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnCoatOfArmsClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnCoatOfArmsRightClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnDynastyCoatOfArmsClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnHouseCoatOfArmsClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnRaidClick", Args::Args(&[DType(Ck3(Raid))]), void),
    ("DefaultOnRealmFlagClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnRealmFlagRightClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnSiegeClick", Args::Args(&[DType(uint32)]), void),
    ("DefaultOnStrugglePhaseClick", Args::Args(&[DType(uint32), DType(Ck3(StrugglePhase))]), void),
    ("Divide_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Divide_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Divide_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector3f),
    ("Divide_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector4f),
    ("Divide_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Divide_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Divide_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("DoubleToFloat", Args::Args(&[DType(double)]), float),
    ("EqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("EqualTo_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), bool),
    ("EqualTo_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("EqualTo_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("EqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("EqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("EqualTo_string", Args::Args(&[DType(CString), DType(CString)]), bool),
    ("EqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("ErrorTooltip", Args::Args(&[]), CString),
    ("ExecuteConsoleCommand", Args::Args(&[DType(CString)]), void),
    ("ExecuteConsoleCommands", Args::Args(&[DType(CString)]), void),
    ("ExecuteConsoleCommandsForced", Args::Args(&[DType(CString)]), void),
    ("FixedPointToFloat", Args::Args(&[DType(CFixedPoint)]), float),
    ("FixedPointToInt", Args::Args(&[DType(CFixedPoint)]), int32),
    ("FixedPointToProgressbarValue", Args::Args(&[DType(CFixedPoint)]), float),
    ("FloatToCVector2f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector2f),
    ("FloatToCVector3f", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CVector3f),
    ("FloatToCVector4f", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown), DType(Unknown)]), CVector4f),
    ("GameHasMultiplePlayers", Args::Args(&[]), bool),
    ("GameIsMultiplayer", Args::Args(&[]), bool),
    ("GameOverDesc", Args::Args(&[]), CString),
    ("GetA_CVector4f", Args::Args(&[DType(Unknown)]), float),
    ("GetA_CVector4i", Args::Args(&[DType(Unknown)]), int32),
    ("GetAbsoluteMousePosition", Args::Args(&[]), CVector2f),
    ("GetAbsoluteMousePositionInteger", Args::Args(&[]), CVector2i),
    ("GetAccoladeType", Args::Args(&[IType(Item::AccoladeType)]), Ck3(AccoladeType)),
    ("GetAchievementsAvailableString", Args::Args(&[]), CString),
    ("GetActivityGroupType", Args::Args(&[DType(Unknown)]), Ck3(ActivityGroupType)),
    ("GetActivityGuestInviteRule", Args::Args(&[IType(Item::GuestInviteRule)]), Ck3(ActivityGuestInviteRule)),
    ("GetActivityIntent", Args::Args(&[IType(Item::ActivityIntent)]), Ck3(ActivityIntent)),
    ("GetActivityLocale", Args::Args(&[IType(Item::ActivityLocale)]), void),
    ("GetActivityPulseAction", Args::Args(&[IType(Item::ActivityPulseAction)]), Ck3(ActivityPulseAction)),
    ("GetActivityType", Args::Args(&[IType(Item::ActivityType)]), Ck3(ActivityType)),
    ("GetAgentSlotType", Args::Args(&[DType(Unknown)]), Ck3(AgentSlotType)),
    ("GetAllAccoladeTypes", Args::Args(&[]), Unknown),
    ("GetAllActivityGroupTypes", Args::Args(&[]), Unknown),
    ("GetAllActivityGuestInviteRules", Args::Args(&[]), Unknown),
    ("GetAllActivityIntents", Args::Args(&[]), Unknown),
    ("GetAllActivityLocales", Args::Args(&[]), Unknown),
    ("GetAllActivityPulseActions", Args::Args(&[]), Unknown),
    ("GetAllActivityTypes", Args::Args(&[]), Unknown),
    ("GetAllAgentSlotTypes", Args::Args(&[]), Unknown),
    ("GetAllArtifactTypes", Args::Args(&[]), Unknown),
    ("GetAllArtifactVisualTypes", Args::Args(&[]), Unknown),
    ("GetAllBookmarkGroups", Args::Args(&[]), Unknown),
    ("GetAllBookmarkPortraits", Args::Args(&[]), Unknown),
    ("GetAllBookmarks", Args::Args(&[]), Unknown),
    ("GetAllBuildings", Args::Args(&[]), Unknown),
    ("GetAllCasusBelliTypes", Args::Args(&[]), Unknown),
    ("GetAllCatalystTypes", Args::Args(&[]), Unknown),
    ("GetAllChallengeCharacters", Args::Args(&[]), Unknown),
    ("GetAllCharacterInteractionCategorys", Args::Args(&[]), Unknown),
    ("GetAllCharacterInteractions", Args::Args(&[]), Unknown),
    ("GetAllCharacterMemoryTypes", Args::Args(&[]), Unknown),
    ("GetAllConfederationTypes", Args::Args(&[]), Unknown),
    ("GetAllConnectionArrowTypes", Args::Args(&[]), Unknown),
    ("GetAllCouncilPositionTypes", Args::Args(&[]), Unknown),
    ("GetAllCouncilTaskTypes", Args::Args(&[]), Unknown),
    ("GetAllCourtAmenitiesSettings", Args::Args(&[]), Unknown),
    ("GetAllCourtPositionTaskTypes", Args::Args(&[]), Unknown),
    ("GetAllCourtPositionTypes", Args::Args(&[]), Unknown),
    ("GetAllCourtTypes", Args::Args(&[]), Unknown),
    ("GetAllCultureEraTypes", Args::Args(&[]), Unknown),
    ("GetAllCultureInnovationTypes", Args::Args(&[]), Unknown),
    ("GetAllCulturePillars", Args::Args(&[]), Unknown),
    ("GetAllCultureTemplates", Args::Args(&[]), Unknown),
    ("GetAllCultureTraditions", Args::Args(&[]), Unknown),
    ("GetAllDecisionGroupTypes", Args::Args(&[]), Unknown),
    ("GetAllDecisions", Args::Args(&[]), Unknown),
    ("GetAllDlcs", Args::Args(&[]), Unknown),
    ("GetAllDomicileBuildings", Args::Args(&[]), Unknown),
    ("GetAllDomicileTypes", Args::Args(&[]), Unknown),
    ("GetAllDynastyHouseTemplates", Args::Args(&[]), Unknown),
    ("GetAllDynastyLegacys", Args::Args(&[]), Unknown),
    ("GetAllDynastyPerks", Args::Args(&[]), Unknown),
    ("GetAllDynastyTemplates", Args::Args(&[]), Unknown),
    ("GetAllEpidemicTypes", Args::Args(&[]), Unknown),
    ("GetAllFaithDoctrineGroups", Args::Args(&[]), Unknown),
    ("GetAllFaithDoctrines", Args::Args(&[]), Unknown),
    ("GetAllFocusTypes", Args::Args(&[]), Unknown),
    ("GetAllGeographicalRegions", Args::Args(&[]), Unknown),
    ("GetAllGovernmentTypes", Args::Args(&[]), Unknown),
    ("GetAllGraphicalUnitTypes", Args::Args(&[]), Unknown),
    ("GetAllGreatProjectTypes", Args::Args(&[]), Unknown),
    ("GetAllHoldingTypes", Args::Args(&[]), Unknown),
    ("GetAllHolySites", Args::Args(&[]), Unknown),
    ("GetAllHouseAspirations", Args::Args(&[]), Unknown),
    ("GetAllHouseRelationLevels", Args::Args(&[]), Unknown),
    ("GetAllHouseRelationTypes", Args::Args(&[]), Unknown),
    ("GetAllHouseUnityStages", Args::Args(&[]), Unknown),
    ("GetAllIllustrations", Args::Args(&[]), Unknown),
    ("GetAllImportantActionTypes", Args::Args(&[]), Unknown),
    ("GetAllInspirationTypes", Args::Args(&[]), Unknown),
    ("GetAllInventorySlotTypes", Args::Args(&[]), Unknown),
    ("GetAllLandedTitpleTemplates", Args::Args(&[]), Unknown),
    ("GetAllLawGroups", Args::Args(&[]), Unknown),
    ("GetAllLaws", Args::Args(&[]), Unknown),
    ("GetAllLegendTypes", Args::Args(&[]), Unknown),
    ("GetAllLegitimacyTypes", Args::Args(&[]), Unknown),
    ("GetAllLifestyles", Args::Args(&[]), Unknown),
    ("GetAllLightTypes", Args::Args(&[]), Unknown),
    ("GetAllMandates", Args::Args(&[]), Unknown),
    ("GetAllMenAtArmsTypes", Args::Args(&[]), Unknown),
    ("GetAllMessageFilterTypes", Args::Args(&[]), Unknown),
    ("GetAllMessageGroupTypes", Args::Args(&[]), Unknown),
    ("GetAllMessageTypes", Args::Args(&[]), Unknown),
    ("GetAllNicknames", Args::Args(&[]), Unknown),
    ("GetAllPerks", Args::Args(&[]), Unknown),
    ("GetAllPortraitTypes", Args::Args(&[]), Unknown),
    ("GetAllRaidIntents", Args::Args(&[]), Unknown),
    ("GetAllReligionFamilys", Args::Args(&[]), Unknown),
    ("GetAllSchemeCountermeasureTypes", Args::Args(&[]), Unknown),
    ("GetAllSchemePulseActions", Args::Args(&[]), Unknown),
    ("GetAllSchemeTypes", Args::Args(&[]), Unknown),
    ("GetAllScriptedRelations", Args::Args(&[]), Unknown),
    ("GetAllSecretTypes", Args::Args(&[]), Unknown),
    ("GetAllSituationCatalystTypes", Args::Args(&[]), Unknown),
    ("GetAllSituationGroupTypes", Args::Args(&[]), Unknown),
    ("GetAllSituationTypes", Args::Args(&[]), Unknown),
    ("GetAllStaticModifiers", Args::Args(&[]), Unknown),
    ("GetAllStrugglePhases", Args::Args(&[]), Unknown),
    ("GetAllStruggleTypes", Args::Args(&[]), Unknown),
    ("GetAllSubjectContractGroups", Args::Args(&[]), Unknown),
    ("GetAllSubjectContractTypes", Args::Args(&[]), Unknown),
    ("GetAllSuggestionTypes", Args::Args(&[]), Unknown),
    ("GetAllTaskContractTypes", Args::Args(&[]), Unknown),
    ("GetAllTaxSlotObligations", Args::Args(&[]), Unknown),
    ("GetAllTaxSlotTypes", Args::Args(&[]), Unknown),
    ("GetAllTerrains", Args::Args(&[]), Unknown),
    ("GetAllTraits", Args::Args(&[]), Unknown),
    ("GetAllTravelOptions", Args::Args(&[]), Unknown),
    ("GetAllTravelPointOfInterestTypes", Args::Args(&[]), Unknown),
    ("GetAllTriggeredLegendSeeds", Args::Args(&[]), Unknown),
    ("GetAllVassalStances", Args::Args(&[]), Unknown),
    ("GetAnimatedBookmarkPortrait", Args::Args(&[DType(CString), DType(CString), DType(CString), DType(CString), DType(CVector2f)]), Unknown),
    ("GetAnimationTooltip", Args::Args(&[DType(Ck3(PdxGuiWidget)), DType(Ck3(Character))]), CString),
    ("GetArtifactType", Args::Args(&[IType(Item::ArtifactType)]), Ck3(ArtifactType)),
    ("GetArtifactVisualType", Args::Args(&[IType(Item::ArtifactVisual)]), Ck3(ArtifactVisualType)),
    ("GetAutosaveName", Args::Args(&[]), CUTF8String),
    ("GetB_CVector4f", Args::Args(&[DType(Unknown)]), float),
    ("GetB_CVector4i", Args::Args(&[DType(Unknown)]), int32),
    ("GetBookmark", Args::Args(&[IType(Item::Bookmark)]), Ck3(Bookmark)),
    ("GetBookmarkGroup", Args::Args(&[IType(Item::BookmarkGroup)]), Ck3(BookmarkGroup)),
    ("GetBookmarkPortrait", Args::Args(&[DType(Unknown)]), Ck3(BookmarkPortrait)),
    ("GetBuildVersionDescription", Args::Args(&[]), CString),
    ("GetBuildVersionDescriptionWithClickToCopy", Args::Args(&[]), CString),
    ("GetBuilding", Args::Args(&[IType(Item::Building)]), Ck3(Building)),
    ("GetCanGoToFrontend", Args::Args(&[]), bool),
    ("GetCanGoToFrontendDesc", Args::Args(&[]), CString),
    ("GetCasusBelliType", Args::Args(&[IType(Item::CasusBelli)]), Ck3(CasusBelliType)),
    ("GetCatalystType", Args::Args(&[IType(Item::Catalyst)]), Ck3(CatalystType)),
    ("GetChallengeCharacter", Args::Args(&[DType(Unknown)]), Ck3(ChallengeCharacter)),
    ("GetCharacterInteraction", Args::Args(&[IType(Item::CharacterInteraction)]), Ck3(CharacterInteraction)),
    ("GetCharacterInteractionCategory", Args::Args(&[IType(Item::CharacterInteractionCategory)]), Ck3(CharacterInteractionCategory)),
    ("GetCharacterMemoryType", Args::Args(&[DType(Unknown)]), void),
    ("GetCoatOfArmsDesignerEmblemTextureCategories", Args::Args(&[]), Unknown),
    ("GetColoredValueString", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("GetCommandDesc", Args::Args(&[DType(Ck3(Command))]), CString),
    ("GetConfederationType", Args::Args(&[DType(Unknown)]), Ck3(ConfederationType)),
    ("GetConnectionArrowType", Args::Args(&[DType(Unknown)]), void),
    ("GetCostString", Args::Args(&[DType(Unknown)]), CString),
    ("GetCostValue", Args::Args(&[DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("GetCouncilPositionType", Args::Args(&[DType(Unknown)]), Ck3(CouncilPositionType)),
    ("GetCouncilTaskType", Args::Args(&[DType(CString)]), Ck3(CouncilTaskType)),
    ("GetCourtAmenitiesSetting", Args::Args(&[DType(Unknown)]), Ck3(CourtAmenitiesSetting)),
    ("GetCourtGrandeurDiffFromExpectedLevelModifier", Args::Args(&[DType(Unknown)]), Ck3(StaticModifier)),
    ("GetCourtGrandeurLevelModifier", Args::Args(&[DType(Unknown)]), Ck3(StaticModifier)),
    ("GetCourtPositionTaskType", Args::Args(&[DType(Unknown)]), Ck3(CourtPositionTaskType)),
    ("GetCourtPositionType", Args::Args(&[DType(CString)]), Ck3(CourtPositionType)),
    ("GetCourtScenePositionForSlot", Args::Args(&[DType(Ck3(PdxGuiWidget)), DType(Ck3(InventorySlot))]), CVector2f),
    ("GetCourtType", Args::Args(&[DType(Unknown)]), Ck3(CourtType)),
    ("GetCreditPortraitsForGroup", Args::Args(&[DType(CString)]), Unknown),
    ("GetCultureEraType", Args::Args(&[DType(Unknown)]), Ck3(CultureEraType)),
    ("GetCultureInnovationType", Args::Args(&[DType(Unknown)]), Ck3(CultureInnovationType)),
    ("GetCulturePillar", Args::Args(&[DType(Unknown)]), Ck3(CulturePillar)),
    ("GetCultureTemplate", Args::Args(&[IType(Item::Culture)]), Ck3(CultureTemplate)),
    ("GetCultureTradition", Args::Args(&[DType(Unknown)]), Ck3(CultureTradition)),
    ("GetCurrentDate", Args::Args(&[]), Date),
    ("GetCurrentDateStringWithSyncInfo", Args::Args(&[]), CString),
    ("GetCurrentDateWithDiff", Args::Args(&[DType(int32)]), CString),
    ("GetCurrentDateWithDiffLong", Args::Args(&[DType(int32)]), CString),
    ("GetCurrentDateWithDiffShort", Args::Args(&[DType(int32)]), CString),
    ("GetCurrentFps", Args::Args(&[]), float),
    ("GetCurrentGameSpeed", Args::Args(&[]), int32),
    ("GetCurrentGameSpeedText", Args::Args(&[]), CString),
    ("GetCurrentHouseUnityStagesDescForLocalPlayer", Args::Args(&[]), CString),
    ("GetCurrentLoadingScreen", Args::Args(&[]), Unknown),
    ("GetDataModelSize", Args::Args(&[DType(Unknown)]), int32),
    ("GetDecision", Args::Args(&[DType(CString)]), Ck3(Decision)),
    ("GetDecisionGroupType", Args::Args(&[DType(Unknown)]), Ck3(DecisionGroupType)),
    ("GetDecisionWithKey", Args::Args(&[IType(Item::Decision)]), Ck3(Decision)),
    ("GetDecisionsForCharacter", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetDecreaseSpeedTooltip", Args::Args(&[]), CString),
    ("GetDefaultServerName", Args::Args(&[]), CUTF8String),
    ("GetDefine", Args::Args(&[DType(CString), DType(CString)]), Unknown),
    ("GetDefineAtIndex", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), Unknown),
    ("GetDisbandAllTooltip", Args::Args(&[]), CString),
    ("GetDlc", Args::Args(&[DType(Unknown)]), Ck3(Dlc)),
    ("GetDomicileBuilding", Args::Args(&[DType(Unknown)]), Ck3(DomicileBuilding)),
    ("GetDomicileType", Args::Args(&[DType(Unknown)]), Ck3(DomicileType)),
    ("GetDynastyHouseTemplate", Args::Args(&[DType(Unknown)]), void),
    ("GetDynastyLegacy", Args::Args(&[DType(Unknown)]), void),
    ("GetDynastyPerk", Args::Args(&[DType(Unknown)]), Ck3(DynastyPerk)),
    ("GetDynastyPrestigeLevelEffect", Args::Args(&[DType(int32)]), CString),
    ("GetDynastyPrestigeLevelName", Args::Args(&[DType(int32)]), CString),
    ("GetDynastyPrestigeLevelNext", Args::Args(&[DType(int32)]), CString),
    ("GetDynastyTemplate", Args::Args(&[DType(Unknown)]), void),
    ("GetEconomyMapModeTooltip", Args::Args(&[DType(Ck3(Province))]), CString),
    ("GetEducationTraits", Args::Args(&[]), Unknown),
    ("GetEnumIndex", Args::Args(&[DType(Unknown)]), CVector2i),
    ("GetEpidemicType", Args::Args(&[DType(Unknown)]), Ck3(EpidemicType)),
    ("GetErrorHoofFrame", Args::Args(&[]), int32),
    ("GetEthnicities", Args::Args(&[]), Unknown),
    ("GetFaithDoctrine", Args::Args(&[IType(Item::Doctrine)]), Ck3(FaithDoctrine)),
    ("GetFaithDoctrineGroup", Args::Args(&[DType(Unknown)]), Ck3(FaithDoctrineGroup)),
    ("GetFertility", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("GetFertilityLevel", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetFocusType", Args::Args(&[DType(Unknown)]), Ck3(FocusType)),
    ("GetG_CVector4f", Args::Args(&[DType(Unknown)]), float),
    ("GetG_CVector4i", Args::Args(&[DType(Unknown)]), int32),
    ("GetGameTimeDifferenceForDiffDays", Args::Args(&[DType(int32)]), CString),
    ("GetGameTimeDifferenceForDiffMonths", Args::Args(&[DType(int32), DType(bool)]), CString),
    ("GetGameTimeDurationDays", Args::Args(&[DType(int32)]), CString),
    ("GetGameTimeDurationMonths", Args::Args(&[DType(Unknown)]), CString),
    ("GetGameVersionDisplay", Args::Args(&[]), CString),
    ("GetGameVersionInfo", Args::Args(&[]), CString),
    ("GetGameVersionInfoShort", Args::Args(&[]), CString),
    ("GetGeneralAptitudeLevel", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetGeographicalRegion", Args::Args(&[IType(Item::Region)]), void),
    ("GetGlobalList", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetGlobalVariable", Args::Args(&[DType(Unknown)]), Scope),
    ("GetGovernment", Args::Args(&[DType(CString)]), Ck3(GovernmentType)),
    ("GetGovernmentType", Args::Args(&[DType(Unknown)]), Ck3(GovernmentType)),
    ("GetGraphicalUnitType", Args::Args(&[DType(Unknown)]), Ck3(GraphicalUnitType)),
    ("GetGreatProjectType", Args::Args(&[DType(Unknown)]), Ck3(GreatProjectType)),
    ("GetGuiPositionFromPercentCoordinates", Args::Args(&[DType(Ck3(PdxGuiWidget)), DType(float), DType(float)]), Unknown),
    ("GetHighlightTint", Args::Args(&[]), CVector4f),
    ("GetHoldingType", Args::Args(&[DType(Unknown)]), Ck3(HoldingType)),
    ("GetHolySite", Args::Args(&[IType(Item::HolySite)]), Ck3(HolySite)),
    ("GetHostError", Args::Args(&[]), CUTF8String),
    ("GetHostilityDescription", Args::Args(&[DType(int32)]), CString),
    ("GetHostilityLevelName", Args::Args(&[DType(int32)]), CString),
    ("GetHouseAspiration", Args::Args(&[IType(Item::HouseAspiration)]), Ck3(HouseAspiration)),
    ("GetHouseRelationLevel", Args::Args(&[IType(Item::HouseRelationLevel)]), Ck3(HouseRelationLevel)),
    ("GetHouseRelationType", Args::Args(&[IType(Item::HouseRelationType)]), Ck3(HouseRelationType)),
    ("GetHouseUnityStage", Args::Args(&[IType(Item::HouseUnityStage)]), Ck3(HouseUnityStage)),
    ("GetIllustration", Args::Args(&[IType(Item::ScriptedIllustration)]), void),
    ("GetImportantActionType", Args::Args(&[IType(Item::ImportantAction)]), Ck3(ImportantActionType)),
    ("GetIncreaseSpeedTooltip", Args::Args(&[]), CString),
    ("GetInfluenceLevelDesc", Args::Args(&[DType(int32)]), CString),
    ("GetInfluenceLevelName", Args::Args(&[DType(int32)]), CString),
    ("GetInspirationType", Args::Args(&[DType(Unknown)]), Ck3(InspirationType)),
    ("GetIntervalCostString", Args::Args(&[DType(Unknown), DType(CString)]), CString),
    ("GetInvParentScale", Args::Args(&[DType(Unknown)]), float),
    ("GetInventorySlotType", Args::Args(&[DType(Unknown)]), Ck3(InventorySlotType)),
    ("GetInventorySlotTypes", Args::Args(&[]), Unknown),
    ("GetIsChecked", Args::Args(&[DType(Unknown)]), bool),
    ("GetKnightCount", Args::Args(&[DType(Ck3(Character))]), int32),
    ("GetKnightLimit", Args::Args(&[DType(Ck3(Character))]), int32),
    ("GetKnightLimitBreakdown", Args::Args(&[DType(Ck3(Character))]), CString),
    ("GetLaggingPlayerName", Args::Args(&[]), CString),
    ("GetLandedTitpleTemplate", Args::Args(&[DType(Unknown)]), void),
    ("GetLaw", Args::Args(&[IType(Item::Law)]), Ck3(Law)),
    ("GetLawGroup", Args::Args(&[IType(Item::LawGroup)]), Ck3(LawGroup)),
    ("GetLeadingTroopsBonus", Args::Args(&[]), CString),
    ("GetLegendType", Args::Args(&[IType(Item::LegendType)]), Ck3(LegendType)),
    ("GetLegitimacyType", Args::Args(&[DType(Unknown)]), Ck3(LegitimacyType)),
    ("GetLifestyle", Args::Args(&[IType(Item::Lifestyle)]), Ck3(Lifestyle)),
    ("GetLifestyleTooltipForCharacter", Args::Args(&[DType(Ck3(Character))]), CString),
    ("GetLifestyleTooltipWarnings", Args::Args(&[DType(Ck3(Character))]), CString),
    ("GetLoadTip", Args::Args(&[]), CString),
    ("GetLoadedMods", Args::Args(&[]), CString),
    ("GetLocalPlayerLegitimacyTextIcon", Args::Args(&[]), CString),
    ("GetLocalPlayerPietyTextIcon", Args::Args(&[]), CString),
    ("GetLocalizedDefine", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("GetLocalizedDefineAtIndex", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CString),
    ("GetLongCostString", Args::Args(&[DType(Unknown)]), CString),
    ("GetMPChecksum", Args::Args(&[]), CString),
    ("GetMandate", Args::Args(&[DType(Unknown)]), void),
    ("GetMaxAppointmentRankDescription", Args::Args(&[DType(CString), DType(int32)]), CString),
    ("GetMaxStress", Args::Args(&[]), int32),
    ("GetMenAtArmsType", Args::Args(&[DType(Unknown)]), Ck3(MenAtArmsType)),
    ("GetMeritLevelEffects", Args::Args(&[DType(int32)]), CString),
    ("GetMeritLevelName", Args::Args(&[DType(int32)]), CString),
    ("GetMeritLevelNameNoTooltip", Args::Args(&[DType(int32)]), CString),
    ("GetMeritLevelShortNameNoTooltip", Args::Args(&[DType(int32)]), CString),
    ("GetMeritLevelThreshold", Args::Args(&[DType(int32)]), CFixedPoint),
    ("GetMessageFilterType", Args::Args(&[DType(Unknown)]), void),
    ("GetMessageGroupType", Args::Args(&[DType(Unknown)]), Ck3(MessageGroupType)),
    ("GetMessageType", Args::Args(&[DType(Unknown)]), Ck3(MessageType)),
    ("GetModifier", Args::Args(&[IType(Item::Modifier)]), Ck3(StaticModifier)),
    ("GetNickname", Args::Args(&[IType(Item::Nickname)]), void),
    ("GetNullCharacter", Args::Args(&[]), Ck3(Character)),
    ("GetNullCharacterDataModel", Args::Args(&[DType(int32)]), Unknown),
    ("GetNullLandedTitle", Args::Args(&[]), Ck3(Title)),
    ("GetNullProperty", Args::Args(&[]), Unknown),
    ("GetNullProvince", Args::Args(&[]), Ck3(Province)),
    ("GetNumberAbove_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("GetNumberOfValidInteractionsWithFilter", Args::Args(&[DType(Ck3(Character)), DType(CString)]), int32),
    ("GetOpenLobbyTooltip", Args::Args(&[]), CString),
    ("GetOpinionTint", Args::Args(&[DType(int32)]), CVector4f),
    ("GetOtherRulerDesignerTraits", Args::Args(&[]), Unknown),
    ("GetPausedBy", Args::Args(&[]), CString),
    ("GetPausedByEventReason", Args::Args(&[]), CString),
    ("GetPerk", Args::Args(&[IType(Item::Perk)]), Ck3(Perk)),
    ("GetPersonalityTraits", Args::Args(&[]), Unknown),
    ("GetPietyLevelDesc", Args::Args(&[DType(int32)]), CString),
    ("GetPietyLevelIcon", Args::Args(&[DType(int32)]), Unknown),
    ("GetPietyLevelName", Args::Args(&[DType(int32)]), CString),
    ("GetPlayer", Args::Args(&[]), Ck3(Character)),
    ("GetPlayerArmyComposition", Args::Args(&[]), Ck3(ArmyComposition)),
    ("GetPlayerRaiseAllBarterersTooltip", Args::Args(&[]), CString),
    ("GetPlayerRaiseAllMenAtArmsTooltip", Args::Args(&[]), CString),
    ("GetPlayerRaiseAllRaidersTooltip", Args::Args(&[]), CString),
    ("GetPlayerRaiseAllTooltip", Args::Args(&[]), CString),
    ("GetPlayersCount", Args::Args(&[]), int32),
    ("GetPortraitTextureFromDna", Args::Args(&[DType(CString), DType(CVector2f)]), Unknown),
    ("GetPortraitType", Args::Args(&[DType(Unknown)]), Ck3(PortraitType)),
    ("GetPrestigeLevelDesc", Args::Args(&[DType(int32)]), CString),
    ("GetPrestigeLevelIcon", Args::Args(&[DType(int32)]), Unknown),
    ("GetPrestigeLevelName", Args::Args(&[DType(int32)]), CString),
    ("GetProgressBarValueMax", Args::Args(&[DType(float), DType(float)]), int32),
    ("GetProgressBarValueMaxOther", Args::Args(&[DType(float), DType(float)]), int32),
    ("GetProgressBarValueMaxOtherScaled", Args::Args(&[DType(float), DType(float), DType(int32)]), int32),
    ("GetProgressBarValueMaxScaled", Args::Args(&[DType(float), DType(float), DType(int32)]), int32),
    ("GetProgressBarValuePair", Args::Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("GetR_CVector4f", Args::Args(&[DType(Unknown)]), float),
    ("GetR_CVector4i", Args::Args(&[DType(Unknown)]), int32),
    ("GetRaidIntent", Args::Args(&[DType(Unknown)]), Ck3(RaidIntent)),
    ("GetRandomFrontendIllustration", Args::Args(&[]), Unknown),
    ("GetRandomLogInfo", Args::Args(&[]), CString),
    ("GetRelation", Args::Args(&[IType(Item::Relation)]), Ck3(ScriptedRelation)),
    ("GetReligionFamily", Args::Args(&[DType(Unknown)]), void),
    ("GetResolutionWithAspectRatio", Args::Args(&[]), CVector2f),
    ("GetRoyalCourtHoveredArtifact", Args::Args(&[]), Ck3(Artifact)),
    ("GetRoyalCourtHoveredCharacter", Args::Args(&[]), Ck3(Character)),
    ("GetRoyalCourtSelectedArtifact", Args::Args(&[]), Ck3(Artifact)),
    ("GetRoyalCourtSelectedCharacter", Args::Args(&[]), Ck3(Character)),
    ("GetSceneSettingsName", Args::Args(&[DType(Unknown)]), CString),
    ("GetSchemeCountermeasureType", Args::Args(&[DType(Unknown)]), Ck3(SchemeCountermeasureType)),
    ("GetSchemeOddsLevelFrameFromValue", Args::Args(&[DType(CFixedPoint)]), int32),
    ("GetSchemeOddsLevelNameFromValue", Args::Args(&[DType(CFixedPoint)]), CString),
    ("GetSchemePulseAction", Args::Args(&[IType(Item::SchemePulseAction)]), void),
    ("GetSchemeType", Args::Args(&[IType(Item::Scheme)]), Ck3(SchemeType)),
    ("GetScriptedRelation", Args::Args(&[IType(Item::Relation)]), Ck3(ScriptedRelation)),
    ("GetSecretType", Args::Args(&[IType(Item::Secret)]), Ck3(SecretType)),
    ("GetSegmentedProgressChanceBar", Args::Args(&[DType(Unknown), DType(Unknown), DType(int32), DType(int32)]), Unknown),
    ("GetSegmentedProgressTargetBar", Args::Args(&[DType(int32), DType(int32), DType(int32)]), Unknown),
    ("GetSituation", Args::Args(&[DType(CString)]), Ck3(Situation)),
    ("GetSituationCatalystType", Args::Args(&[DType(Unknown)]), Ck3(SituationCatalystType)),
    ("GetSituationGroupType", Args::Args(&[DType(Unknown)]), Ck3(SituationGroupType)),
    ("GetSituationOfType", Args::Args(&[DType(Unknown)]), Ck3(Situation)),
    ("GetSituationType", Args::Args(&[DType(Unknown)]), Ck3(SituationType)),
    ("GetSmartBrushInterpolationNames", Args::Args(&[]), Unknown),
    ("GetSmartBrushPatternNames", Args::Args(&[]), Unknown),
    ("GetStaticModifier", Args::Args(&[IType(Item::Modifier)]), Ck3(StaticModifier)),
    ("GetStringSettingText", Args::Args(&[DType(Unknown)]), CString),
    ("GetString_CPdxFloatRect", Args::Args(&[DType(Ck3(CPdxFloatRect))]), CString),
    ("GetString_CPdxIntRect", Args::Args(&[DType(Ck3(CPdxIntRect))]), CString),
    ("GetString_CUTF8String", Args::Args(&[DType(CUTF8String)]), CString),
    ("GetString_CVector2f", Args::Args(&[DType(CVector2f)]), CString),
    ("GetString_CVector2i", Args::Args(&[DType(CVector2i)]), CString),
    ("GetString_CVector3f", Args::Args(&[DType(CVector3f)]), CString),
    ("GetString_CVector3i", Args::Args(&[DType(CVector3i)]), CString),
    ("GetString_CVector4f", Args::Args(&[DType(CVector4f)]), CString),
    ("GetString_CVector4i", Args::Args(&[DType(CVector4i)]), CString),
    ("GetStruggle", Args::Args(&[DType(Unknown)]), Ck3(Struggle)),
    ("GetStrugglePhase", Args::Args(&[DType(Unknown)]), Ck3(StrugglePhase)),
    ("GetStruggleType", Args::Args(&[DType(Unknown)]), Ck3(StruggleType)),
    ("GetSubjectContractGroup", Args::Args(&[DType(Unknown)]), Ck3(SubjectContractGroup)),
    ("GetSubjectContractType", Args::Args(&[DType(Unknown)]), Ck3(SubjectContractType)),
    ("GetSuggestionType", Args::Args(&[DType(Unknown)]), Ck3(SuggestionType)),
    ("GetTaskContractType", Args::Args(&[DType(Unknown)]), Ck3(TaskContractType)),
    ("GetTaxSlotObligation", Args::Args(&[DType(Unknown)]), Ck3(TaxSlotObligation)),
    ("GetTaxSlotType", Args::Args(&[DType(Unknown)]), Ck3(TaxSlotType)),
    ("GetTerrain", Args::Args(&[IType(Item::Terrain)]), Ck3(Terrain)),
    ("GetTicksSinceLastProgress", Args::Args(&[DType(uint32), DType(int32)]), int32),
    ("GetTimeAnyoneUnpause", Args::Args(&[]), int32),
    ("GetTimeBetweenDates", Args::Args(&[DType(Date), DType(Date)]), CString),
    ("GetTimeDifferenceWithDays", Args::Args(&[DType(int32)]), CString),
    ("GetToggleCompanionAICommand", Args::Args(&[]), Ck3(Command)),
    ("GetTotalDaysInMonth", Args::Args(&[DType(Unknown)]), int32),
    ("GetTrait", Args::Args(&[IType(Item::Trait)]), Ck3(Trait)),
    ("GetTraitGroup", Args::Args(&[DType(Unknown)]), Ck3(TraitGroup)),
    ("GetTraits", Args::Args(&[]), Unknown),
    ("GetTraitsWithFlag", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetTraitsWithoutFlag", Args::Args(&[DType(Unknown)]), Unknown),
    ("GetTravelOption", Args::Args(&[DType(Unknown)]), Ck3(TravelOption)),
    ("GetTravelPointOfInterestType", Args::Args(&[DType(Unknown)]), void),
    ("GetTriggeredLegendSeed", Args::Args(&[DType(Unknown)]), void),
    ("GetVarTimeRemaining", Args::Args(&[DType(Scope), DType(CString)]), int32),
    ("GetVassalStance", Args::Args(&[IType(Item::VassalStance)]), Ck3(VassalStance)),
    ("GetViewHistoryTooltip", Args::Args(&[]), CString),
    ("GetW_CVector4f", Args::Args(&[DType(CVector4f)]), float),
    ("GetW_CVector4i", Args::Args(&[DType(CVector4i)]), int32),
    ("GetX_CVector2f", Args::Args(&[DType(CVector2f)]), float),
    ("GetX_CVector2i", Args::Args(&[DType(CVector2i)]), int32),
    ("GetX_CVector3f", Args::Args(&[DType(CVector3f)]), float),
    ("GetX_CVector3i", Args::Args(&[DType(CVector3i)]), int32),
    ("GetX_CVector4f", Args::Args(&[DType(CVector4f)]), float),
    ("GetX_CVector4i", Args::Args(&[DType(CVector4i)]), int32),
    ("GetY_CVector2f", Args::Args(&[DType(CVector2f)]), float),
    ("GetY_CVector2i", Args::Args(&[DType(CVector2i)]), int32),
    ("GetY_CVector3f", Args::Args(&[DType(CVector3f)]), float),
    ("GetY_CVector3i", Args::Args(&[DType(CVector3i)]), int32),
    ("GetY_CVector4f", Args::Args(&[DType(CVector4f)]), float),
    ("GetY_CVector4i", Args::Args(&[DType(CVector4i)]), int32),
    ("GetZ_CVector3f", Args::Args(&[DType(CVector3f)]), float),
    ("GetZ_CVector3i", Args::Args(&[DType(CVector3i)]), int32),
    ("GetZ_CVector4f", Args::Args(&[DType(CVector4f)]), float),
    ("GetZ_CVector4i", Args::Args(&[DType(CVector4i)]), int32),
    ("GetZoomLevel", Args::Args(&[]), int32),
    ("Get_CVector2f", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("Get_CVector2i", Args::Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("Get_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("Get_CVector3i", Args::Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("Get_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), float),
    ("Get_CVector4i", Args::Args(&[DType(Unknown), DType(Unknown)]), int32),
    ("GfxGetSkins", Args::Args(&[]), Unknown),
    ("GfxSetActiveSkin", Args::Args(&[DType(CString)]), void),
    ("GfxSkinIsActive", Args::Args(&[DType(CString)]), bool),
    ("Glossary", Args::Args(&[DType(CString), DType(CString)]), CString),
    ("GoToFrontend", Args::Args(&[]), void),
    ("GreaterThanOrEqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("GreaterThanOrEqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("GreaterThanOrEqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("GreaterThanOrEqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("GreaterThan_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("GreaterThan_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("GreaterThan_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("GreaterThan_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("HasCharacterInteractionCategory", Args::Args(&[DType(Unknown)]), bool),
    ("HasDifferentChecksumThanCompiled", Args::Args(&[]), bool),
    ("HasDlcFeature", Args::Args(&[IType(Item::DlcFeature)]), bool),
    ("HasErrors", Args::Args(&[]), bool),
    ("HasGameStartedForTheFirstTime", Args::Args(&[]), bool),
    ("HasHostError", Args::Args(&[]), bool),
    ("HasLoadedMods", Args::Args(&[]), bool),
    ("HasOpenResetReactiveTutorialPopup", Args::Args(&[]), bool),
    ("HasOpenSuccession", Args::Args(&[DType(Ck3(Character))]), bool),
    ("HasViewHistory", Args::Args(&[]), bool),
    ("HighlightStruggle", Args::Args(&[DType(Ck3(Struggle))]), void),
    ("HoursPerDay", Args::Args(&[]), int32),
    ("InDebugMode", Args::Args(&[]), bool),
    ("InReleaseMode", Args::Args(&[]), bool),
    ("Int32ToCVector2i", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector2i),
    ("Int32ToCVector3i", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown)]), CVector3i),
    ("Int32ToCVector4i", Args::Args(&[DType(Unknown), DType(Unknown), DType(Unknown), DType(Unknown)]), CVector4i),
    ("IntToFixedPoint", Args::Args(&[DType(int32)]), CFixedPoint),
    ("IntToFloat", Args::Args(&[DType(int32)]), float),
    ("IntToFrameIndex", Args::Args(&[DType(int32)]), int32),
    ("IntToUnsigned", Args::Args(&[DType(int32)]), uint32),
    ("IsAdminVassalDetailViewShown", Args::Args(&[DType(Ck3(Title))]), bool),
    ("IsAdministrativeArmyDetailViewShown", Args::Args(&[DType(Unknown)]), bool),
    ("IsAltDown", Args::Args(&[]), bool),
    ("IsAnySituationViewOpen", Args::Args(&[]), bool),
    ("IsAutoSaving", Args::Args(&[]), bool),
    ("IsBottomLeftWindowOpen", Args::Args(&[]), bool),
    ("IsBottomWindowOpen", Args::Args(&[]), bool),
    ("IsBuildDebug", Args::Args(&[]), bool),
    ("IsCameraRestrictionsEnabled", Args::Args(&[]), bool),
    ("IsCenterWindowOpen", Args::Args(&[]), bool),
    ("IsContractBlockedFromBeingModified", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("IsContractBlockedFromBeingModifiedText", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("IsCostEmpty", Args::Args(&[DType(Unknown), DType(Unknown)]), CFixedPoint),
    ("IsCtrlDown", Args::Args(&[]), bool),
    ("IsDataModelEmpty", Args::Args(&[DType(Unknown)]), bool),
    ("IsDateAfter", Args::Args(&[DType(Date), DType(Date)]), bool),
    ("IsDateBefore", Args::Args(&[DType(Date), DType(Date)]), bool),
    ("IsDateBetween", Args::Args(&[DType(Date), DType(Date), DType(Date)]), bool),
    ("IsDateToday", Args::Args(&[DType(Date)]), bool),
    ("IsDefaultGUIMode", Args::Args(&[]), bool),
    ("IsDesignatedHeir", Args::Args(&[DType(Ck3(Character))]), bool),
    ("IsExploringHouses", Args::Args(&[]), bool),
    ("IsExploringRealms", Args::Args(&[]), bool),
    ("IsFullScreenWindowOpen", Args::Args(&[]), bool),
    ("IsGameChecksumOk", Args::Args(&[]), bool),
    ("IsGameOver", Args::Args(&[]), bool),
    ("IsGamePaused", Args::Args(&[]), bool),
    ("IsGameViewDataShown", Args::Args(&[DType(CString), DType(Unknown)]), bool),
    ("IsGameViewOpen", Args::Args(&[DType(CString)]), bool),
    ("IsHireableRulerDetailViewShown", Args::Args(&[DType(Ck3(Character))]), bool),
    ("IsHolyOrderDetailViewShown", Args::Args(&[DType(Ck3(HolyOrder))]), bool),
    ("IsHost", Args::Args(&[]), bool),
    ("IsInGame", Args::Args(&[]), bool),
    ("IsInteractionConfirmationWindowOpen", Args::Args(&[]), bool),
    ("IsInteractionMenuOpenForCharacter", Args::Args(&[DType(uint32)]), bool),
    ("IsInteractionMenuOpenForCharacterWithFilter", Args::Args(&[DType(Ck3(Character)), DType(CString)]), bool),
    ("IsIronmanEnabled", Args::Args(&[]), bool),
    ("IsLeftWindowOpen", Args::Args(&[]), bool),
    ("IsMachineRulerDesigning", Args::Args(&[DType(Unknown)]), bool),
    ("IsManuallyPaused", Args::Args(&[]), bool),
    ("IsMapInteractionConfirmationWindowOpen", Args::Args(&[]), bool),
    ("IsMapMode", Args::Args(&[IType(Item::MapMode)]), bool),
    ("IsMercenaryCompanyDetailViewShown", Args::Args(&[DType(Ck3(MercenaryCompany))]), bool),
    ("IsObserver", Args::Args(&[]), bool),
    ("IsOverviewWindowOpen", Args::Args(&[]), bool),
    ("IsPauseMenuShown", Args::Args(&[]), bool),
    ("IsPausedByEvent", Args::Args(&[]), bool),
    ("IsPausedByMe", Args::Args(&[]), bool),
    ("IsPausedBySuccession", Args::Args(&[]), bool),
    ("IsPreparationLobby", Args::Args(&[]), bool),
    ("IsRightSubwindowOpen", Args::Args(&[]), bool),
    ("IsRightWindowNoSidebarOpen", Args::Args(&[]), bool),
    ("IsRightWindowOpen", Args::Args(&[]), bool),
    ("IsShiftDown", Args::Args(&[]), bool),
    ("IsSituationPriority", Args::Args(&[DType(Ck3(Situation)), DType(CString)]), bool),
    ("IsStrugglePriority", Args::Args(&[DType(Ck3(Struggle)), DType(CString)]), bool),
    ("IsTutorialTagOpen", Args::Args(&[DType(Unknown)]), bool),
    ("IsValidCommand", Args::Args(&[DType(Ck3(Command))]), bool),
    ("IsValidDate", Args::Args(&[DType(Date)]), bool),
    ("JoinText", Args::Args(&[DType(CString), DType(CString), DType(CString)]), CString),
    ("JominiAccessPlayerJoinRequests", Args::Args(&[]), Unknown),
    ("JominiAreAchievementsAvailable", Args::Args(&[]), bool),
    ("JominiGetAchievementsNotAvailableString", Args::Args(&[]), CString),
    ("JominiGetMultiplayerAccessibleString", Args::Args(&[]), CString),
    ("JominiHasPlayerJoinRequests", Args::Args(&[]), bool),
    ("JominiIsHostOrLocal", Args::Args(&[]), bool),
    ("JominiIsMultiplayerAccessible", Args::Args(&[]), bool),
    ("JominiMultiplayerIsCrossplayEnabled", Args::Args(&[]), bool),
    ("JominiMultiplayerIsCrossplayFilterAvailable", Args::Args(&[]), bool),
    ("JominiPlayer", Args::Args(&[]), Ck3(Playable)),
    ("LessThanOrEqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("LessThanOrEqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("LessThanOrEqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("LessThanOrEqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("LessThan_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("LessThan_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("LessThan_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("LessThan_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("LiveMode", Args::Args(&[]), bool),
    ("Localize", Args::Args(&[DType(CString)]), CString),
    ("MakeScopeBool", Args::Args(&[DType(Unknown)]), Scope),
    ("MakeScopeFlag", Args::Args(&[DType(Unknown)]), Scope),
    ("MakeScopeValue", Args::Args(&[DType(Unknown)]), Scope),
    ("MapEditorHasGameMapMode", Args::Args(&[]), bool),
    ("Max_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Max_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Max_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Max_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Min_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Min_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Min_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Min_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("Modulo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Modulo_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Modulo_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector3f),
    ("Modulo_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector4f),
    ("Modulo_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Modulo_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Modulo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("MonthsPerYear", Args::Args(&[]), int32),
    ("Multiply_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Multiply_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Multiply_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector3f),
    ("Multiply_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector4f),
    ("Multiply_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Multiply_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Multiply_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("NOP", Args::Args(&[]), void),
    ("Nbsp", Args::Args(&[]), CString),
    ("Negate_CFixedPoint", Args::Args(&[DType(CFixedPoint)]), CFixedPoint),
    ("Negate_float", Args::Args(&[DType(float)]), float),
    ("Negate_int32", Args::Args(&[DType(int32)]), int32),
    ("Not", Args::Args(&[DType(bool)]), bool),
    ("NotEqualTo_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), bool),
    ("NotEqualTo_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), bool),
    ("NotEqualTo_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("NotEqualTo_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("NotEqualTo_float", Args::Args(&[DType(float), DType(float)]), bool),
    ("NotEqualTo_int32", Args::Args(&[DType(int32), DType(int32)]), bool),
    ("NotEqualTo_uint32", Args::Args(&[DType(uint32), DType(uint32)]), bool),
    ("NumberOrErrors", Args::Args(&[]), int32),
    ("ObjectsEqual", Args::Args(&[DType(Unknown), DType(Unknown)]), bool),
    ("OnCreateAccount", Args::Args(&[]), void),
    ("OnDecreaseGameSpeed", Args::Args(&[]), void),
    ("OnGoToPlayerCapital", Args::Args(&[]), void),
    ("OnIncreaseGameSpeed", Args::Args(&[]), void),
    ("OnPause", Args::Args(&[]), void),
    ("OnPauseMenu", Args::Args(&[]), void),
    ("OnRaiseEventTroops", Args::Args(&[DType(Ck3(MilitaryViewEventTroop))]), void),
    ("OnToggleLoginWindow", Args::Args(&[]), void),
    ("OpenAchievements", Args::Args(&[]), void),
    ("OpenAdminVassalDetailView", Args::Args(&[DType(Ck3(Title))]), void),
    ("OpenAdministrativeArmyDetailView", Args::Args(&[DType(Ck3(Title))]), void),
    ("OpenCharacterInteraction", Args::Args(&[DType(CString), DType(Ck3(Character))]), void),
    ("OpenDesignateHeirWindow", Args::Args(&[]), Unknown),
    ("OpenDynastyCustomizationWindow", Args::Args(&[DType(Ck3(Dynasty))]), void),
    ("OpenErrorLog", Args::Args(&[]), void),
    ("OpenFromViewHistory", Args::Args(&[]), void),
    ("OpenGameRules", Args::Args(&[]), void),
    ("OpenGameView", Args::Args(&[DType(CString)]), void),
    ("OpenGameViewData", Args::Args(&[DType(CString), DType(Unknown)]), void),
    ("OpenGuiTab", Args::Args(&[DType(CString), DType(CString)]), void),
    ("OpenHireableRulerDetailView", Args::Args(&[DType(Ck3(Character))]), void),
    ("OpenHolyOrderDetailView", Args::Args(&[DType(Ck3(HolyOrder))]), void),
    ("OpenHouseCustomizationWindow", Args::Args(&[DType(Ck3(DynastyHouse))]), void),
    ("OpenMercenaryCompanyDetailView", Args::Args(&[DType(Unknown)]), void),
    ("OpenSetAcclaimedView", Args::Args(&[DType(Unknown)]), void),
    ("OpenSuccessionElectionWindowForTitle", Args::Args(&[DType(Ck3(Title))]), Unknown),
    ("OpenSuccessionLawChangeWindow", Args::Args(&[DType(Ck3(GuiLawGroup))]), Unknown),
    ("OpenTitleCustomizationWindow", Args::Args(&[DType(Ck3(Title))]), void),
    ("OpenTitleWindowAndGrantTitle", Args::Args(&[DType(Unknown)]), void),
    ("Or", Args::Args(&[DType(bool), DType(bool)]), bool),
    ("POPSStatusGetLoginStatus", Args::Args(&[]), CUTF8String),
    ("POPSStatusIsAccountConnected", Args::Args(&[]), bool),
    ("POPSStatusIsLoggedIn", Args::Args(&[]), bool),
    ("POPSStatusIsLoggingIn", Args::Args(&[]), bool),
    ("POPSStatusIsOffline", Args::Args(&[]), bool),
    ("POPSStatusIsSupportConnectedAccount", Args::Args(&[]), bool),
    ("POPStatusGetUserEmailMasked", Args::Args(&[]), CUTF8String),
    ("POPStatusGetUserName", Args::Args(&[]), CUTF8String),
    ("POPStatusIsUserNameEmpty", Args::Args(&[]), bool),
    ("PdxClearEditBoxText", Args::Args(&[DType(Unknown)]), void),
    ("PdxGetProfilerNames", Args::Args(&[]), Unknown),
    ("PdxGetWidgetScreenSize", Args::Args(&[DType(Ck3(PdxGuiWidget))]), CVector2f),
    ("PdxGuiDestroyWidget", Args::Args(&[DType(Ck3(PdxGuiWidget))]), void),
    ("PdxGuiEditorMessageBox", Args::Args(&[DType(Unknown)]), void),
    ("PdxGuiInterruptAllAnimations", Args::Args(&[DType(CString)]), void),
    ("PdxGuiInterruptThenTriggerAllAnimations", Args::Args(&[DType(CString), DType(CString)]), void),
    ("PdxGuiTriggerAllAnimations", Args::Args(&[DType(CString)]), void),
    ("PdxProfilerFilterNext", Args::Args(&[]), void),
    ("PdxProfilerFilterPrev", Args::Args(&[]), void),
    ("PdxProfilerFilterTimers", Args::Args(&[]), void),
    ("PdxProfilerGetCurrentFrame", Args::Args(&[]), int32),
    ("PdxProfilerGetFrameTimeMs", Args::Args(&[]), float),
    ("PdxProfilerGetNsPerTick", Args::Args(&[]), float),
    ("PdxProfilerGuiGraphLinesEnabled", Args::Args(&[]), bool),
    ("PdxProfilerGuiToggleGraphLines", Args::Args(&[]), void),
    ("PdxProfilerGuiToggleStats", Args::Args(&[]), void),
    ("PdxProfilerGuiTrackCurrentFrame", Args::Args(&[]), void),
    ("PdxProfilerGuiWriteFrameCSV", Args::Args(&[]), void),
    ("PdxProfilerIsRecording", Args::Args(&[]), bool),
    ("PdxProfilerSelectThread", Args::Args(&[]), void),
    ("PdxProfilerSetFrame", Args::Args(&[]), void),
    ("PdxProfilerToggleRecording", Args::Args(&[]), void),
    ("PinSituation", Args::Args(&[DType(Ck3(Situation)), DType(CString)]), Ck3(Command)),
    ("PinStruggle", Args::Args(&[DType(Ck3(Struggle)), DType(CString)]), Ck3(Command)),
    ("PlaySfxEvent", Args::Args(&[DType(CString)]), void),
    ("PlayerCanDisbandAll", Args::Args(&[]), bool),
    ("PlayerCanRaiseAnyBarterRallyPoint", Args::Args(&[]), bool),
    ("PlayerCanRaiseAnyMenAtArmsRallyPoint", Args::Args(&[]), bool),
    ("PlayerCanRaiseAnyRaiderRallyPoint", Args::Args(&[]), bool),
    ("PlayerCanRaiseAnyRallyPoint", Args::Args(&[]), bool),
    ("PlayerDisbandAll", Args::Args(&[]), void),
    ("PlayerIsHost", Args::Args(&[]), bool),
    ("PlayerRaiseAllBarterRegiments", Args::Args(&[]), void),
    ("PlayerRaiseAllBarterRegimentsAtLocation", Args::Args(&[]), void),
    ("PlayerRaiseAllMenAtArmsRegiments", Args::Args(&[]), void),
    ("PlayerRaiseAllMenAtArmsRegimentsAtLocation", Args::Args(&[]), void),
    ("PlayerRaiseAllRaidRegiments", Args::Args(&[]), void),
    ("PlayerRaiseAllRaidRegimentsAtLocation", Args::Args(&[]), void),
    ("PlayerRaiseAllRegiments", Args::Args(&[]), void),
    ("PlayerRaiseAllRegimentsAtLocation", Args::Args(&[]), void),
    ("PlayerShouldDisbandAll", Args::Args(&[]), bool),
    ("PostCommand", Args::Args(&[DType(Ck3(Command))]), void),
    ("PreSelectDecisionOption", Args::Args(&[DType(CString)]), void),
    ("RaiseHolyOrder", Args::Args(&[DType(Unknown)]), void),
    ("RaiseMercenaryCompany", Args::Args(&[DType(Ck3(MercenaryCompany))]), void),
    ("RefreshIllustration", Args::Args(&[]), void),
    ("ReleaseMode", Args::Args(&[]), bool),
    ("RepeatedItem", Args::Args(&[DType(Unknown)]), Unknown),
    ("ReturnToMenu", Args::Args(&[]), void),
    ("ScaleToFitElementInside", Args::Args(&[DType(int32), DType(int32)]), float),
    ("ScaleToFitElementOutside", Args::Args(&[DType(int32), DType(int32)]), float),
    ("SelectEnumWithString", Args::Args(&[DType(CString), DType(Unknown)]), void),
    ("SelectLocalization", Args::Args(&[DType(bool), DType(CString), DType(CString)]), CString),
    ("Select_CFixedPoint", Args::Args(&[DType(bool), DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Select_CString", Args::Args(&[DType(bool), DType(CString), DType(CString)]), CString),
    ("Select_CVector2f", Args::Args(&[DType(bool), DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Select_CVector2i", Args::Args(&[DType(bool), DType(CVector2i), DType(CVector2i)]), CVector2i),
    ("Select_CVector3f", Args::Args(&[DType(bool), DType(CVector3f), DType(CVector3f)]), CVector3f),
    ("Select_CVector3i", Args::Args(&[DType(bool), DType(CVector3i), DType(CVector3i)]), CVector3i),
    ("Select_CVector4f", Args::Args(&[DType(bool), DType(CVector4f), DType(CVector4f)]), CVector4f),
    ("Select_CVector4i", Args::Args(&[DType(bool), DType(CVector4i), DType(CVector4i)]), CVector4i),
    ("Select_float", Args::Args(&[DType(bool), DType(float), DType(float)]), float),
    ("Select_int16", Args::Args(&[DType(bool), DType(int16), DType(int16)]), int16),
    ("Select_int32", Args::Args(&[DType(bool), DType(int32), DType(int32)]), int32),
    ("Select_int8", Args::Args(&[DType(bool), DType(int8), DType(int8)]), int8),
    ("Select_uint16", Args::Args(&[DType(bool), DType(uint16), DType(uint16)]), uint16),
    ("Select_uint32", Args::Args(&[DType(bool), DType(uint32), DType(uint32)]), uint32),
    ("Select_uint8", Args::Args(&[DType(bool), DType(uint8), DType(uint8)]), uint8),
    ("SetAdminVassalDetailCandidate", Args::Args(&[DType(Ck3(Character))]), void),
    ("SetCameraRestrictionsEnabled", Args::Args(&[DType(bool)]), void),
    ("SetGameSpeed", Args::Args(&[DType(int32)]), void),
    ("SetIronmanEnabledStatus", Args::Args(&[DType(bool)]), void),
    ("SetMapMode", Args::Args(&[DType(CString)]), void),
    ("SetRandomPlayableObserverCharacter", Args::Args(&[]), void),
    ("ShouldPromptForRulerDesigner", Args::Args(&[]), bool),
    ("ShouldShowAnimationInfo", Args::Args(&[]), bool),
    ("ShouldShowCharacterDebugInfo", Args::Args(&[]), bool),
    ("ShouldShowCharacterTooltips", Args::Args(&[]), bool),
    ("ShouldShowSegmentedControlForSetting", Args::Args(&[DType(Unknown)]), bool),
    ("ShowAppointCourtPosition", Args::Args(&[DType(Unknown), DType(Unknown)]), void),
    ("ShowAppointCourtPositionIfNoEmployee", Args::Args(&[DType(uint32), DType(CString)]), void),
    ("ShowCourtPositionAppointOrReplace", Args::Args(&[DType(uint32), DType(CString)]), void),
    ("ShowCourtPositions", Args::Args(&[DType(Unknown)]), void),
    ("ShowDetailedBarterMapIcons", Args::Args(&[]), bool),
    ("ShowDetailedRaidMapIcons", Args::Args(&[]), bool),
    ("ShowEpidemicMapGraphics", Args::Args(&[]), bool),
    ("ShowLegendMapGraphics", Args::Args(&[]), bool),
    ("ShowingSuccession", Args::Args(&[]), bool),
    ("SinglePlayerShowingPausedSuccession", Args::Args(&[]), bool),
    ("SinglePlayerShowingSuccession", Args::Args(&[]), bool),
    ("StringIsEmpty", Args::Args(&[DType(CString)]), bool),
    ("Subtract_CFixedPoint", Args::Args(&[DType(CFixedPoint), DType(CFixedPoint)]), CFixedPoint),
    ("Subtract_CVector2f", Args::Args(&[DType(CVector2f), DType(CVector2f)]), CVector2f),
    ("Subtract_CVector3f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector3f),
    ("Subtract_CVector4f", Args::Args(&[DType(Unknown), DType(Unknown)]), CVector4f),
    ("Subtract_float", Args::Args(&[DType(float), DType(float)]), float),
    ("Subtract_int32", Args::Args(&[DType(int32), DType(int32)]), int32),
    ("Subtract_uint32", Args::Args(&[DType(uint32), DType(uint32)]), uint32),
    ("TextureListFormatSize", Args::Args(&[DType(uint64)]), CString),
    ("TextureListFormatkB", Args::Args(&[DType(uint64)]), CString),
    ("ToTextFormatColor", Args::Args(&[DType(CVector4f)]), CString),
    ("ToggleAdminVassalDetailView", Args::Args(&[DType(Ck3(Title))]), void),
    ("ToggleAdministrativeArmyDetailView", Args::Args(&[DType(Unknown)]), void),
    ("ToggleEncyclopedia", Args::Args(&[]), void),
    ("ToggleFilteredCharacterInteractionMenu", Args::Args(&[DType(Ck3(Character)), DType(CString)]), void),
    ("ToggleGameView", Args::Args(&[DType(CString)]), void),
    ("ToggleGameViewData", Args::Args(&[DType(CString), DType(Unknown)]), void),
    ("ToggleHireableRulerDetailView", Args::Args(&[DType(Unknown)]), void),
    ("ToggleHolyOrderDetailView", Args::Args(&[DType(Unknown)]), void),
    ("ToggleMapEditorGameMapModeActive", Args::Args(&[]), void),
    ("ToggleMapMode", Args::Args(&[DType(CString)]), void),
    ("ToggleMercenaryCompanyDetailView", Args::Args(&[DType(Ck3(MercenaryCompany))]), void),
    ("ToggleMessageSettings", Args::Args(&[]), void),
    ("ToggleMusicPlayer", Args::Args(&[]), void),
    ("ToggleOnCoatOfArmsClick", Args::Args(&[DType(Unknown)]), void),
    ("ToggleShowDetailedBarterMapIcons", Args::Args(&[]), void),
    ("ToggleShowDetailedRaidMapIcons", Args::Args(&[]), void),
    ("ToggleShowEpidemicMapGraphics", Args::Args(&[]), void),
    ("ToggleShowLegendMapGraphics", Args::Args(&[]), void),
    ("TrimBack", Args::Args(&[DType(CString)]), CString),
    ("TrimBackChars", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("TrimFront", Args::Args(&[DType(Unknown)]), CString),
    ("TrimFrontChars", Args::Args(&[DType(Unknown), DType(Unknown)]), CString),
    ("TryStartRulerDesigning", Args::Args(&[DType(Ck3(Character)), DType(CString)]), void),
    ("Unfocus", Args::Args(&[DType(Unknown)]), void),
    ("UpdatePlayerRulerObjectiveAdvice", Args::Args(&[]), Ck3(Command)),
    ("UsesTimerLocking", Args::Args(&[]), bool),
    ("WatchWindowsEnabled", Args::Args(&[]), bool),
    ("WeeksPerYear", Args::Args(&[]), int32),
]
