/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  aux_sym_definition_token1 = 2,
  sym_identifier = 3,
  anon_sym_DOLLAR = 4,
  aux_sym_macro_token1 = 5,
  anon_sym_LBRACK = 6,
  aux_sym_expression_token1 = 7,
  anon_sym_RBRACK = 8,
  anon_sym_POUND = 9,
  aux_sym_format_token1 = 10,
  anon_sym_SPACE = 11,
  aux_sym_format_token2 = 12,
  anon_sym_POUND_BANG = 13,
  anon_sym_LF = 14,
  anon_sym_CR_LF = 15,
  sym_source_file = 16,
  sym_top_key = 17,
  sym__lines = 18,
  sym_definition = 19,
  sym_text = 20,
  sym_macro = 21,
  sym_expression = 22,
  sym_format = 23,
  sym_string = 24,
  sym_comment = 25,
  aux_sym__terminator = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_text_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [aux_sym_definition_token1] = "version",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_macro_token1] = "macro_token1",
  [anon_sym_LBRACK] = "[",
  [aux_sym_expression_token1] = "expression_token1",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND] = "#",
  [aux_sym_format_token1] = "format_tag",
  [anon_sym_SPACE] = " ",
  [aux_sym_format_token2] = "format_content",
  [anon_sym_POUND_BANG] = "#!",
  [anon_sym_LF] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [sym_source_file] = "source_file",
  [sym_top_key] = "top_key",
  [sym__lines] = "_lines",
  [sym_definition] = "definition",
  [sym_text] = "text",
  [sym_macro] = "macro",
  [sym_expression] = "expression",
  [sym_format] = "format",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [aux_sym__terminator] = "_terminator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_definition_token1] = aux_sym_definition_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_macro_token1] = aux_sym_macro_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_format_token1] = aux_sym_format_token1,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_format_token2] = aux_sym_format_token2,
  [anon_sym_POUND_BANG] = anon_sym_POUND_BANG,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [sym_source_file] = sym_source_file,
  [sym_top_key] = sym_top_key,
  [sym__lines] = sym__lines,
  [sym_definition] = sym_definition,
  [sym_text] = sym_text,
  [sym_macro] = sym_macro,
  [sym_expression] = sym_expression,
  [sym_format] = sym_format,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [aux_sym__terminator] = aux_sym__terminator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_definition_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_format_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_format_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_top_key] = {
    .visible = true,
    .named = true,
  },
  [sym__lines] = {
    .visible = false,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__terminator] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == '[') ADVANCE(15);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\t') SKIP(1);
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(20);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_definition_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_definition_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(14);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_macro_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_macro_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_macro_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_format_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_format_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_format_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_POUND_BANG);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 22},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 13},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_definition_token1] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym_top_key] = STATE(5),
    [sym_identifier] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_POUND,
    STATE(3), 1,
      aux_sym_text_repeat1,
    ACTIONS(5), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(26), 3,
      sym_macro,
      sym_expression,
      sym_format,
  [23] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(16), 1,
      anon_sym_POUND,
    STATE(4), 1,
      aux_sym_text_repeat1,
    ACTIONS(14), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(26), 3,
      sym_macro,
      sym_expression,
      sym_format,
  [46] = 6,
    ACTIONS(21), 1,
      anon_sym_DOLLAR,
    ACTIONS(24), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(4), 1,
      aux_sym_text_repeat1,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(26), 3,
      sym_macro,
      sym_expression,
      sym_format,
  [69] = 5,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_POUND,
    STATE(6), 2,
      sym__lines,
      aux_sym_source_file_repeat1,
    STATE(19), 2,
      sym_definition,
      sym_comment,
  [87] = 5,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_POUND,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym__lines,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_definition,
      sym_comment,
  [105] = 5,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_POUND,
    STATE(7), 2,
      sym__lines,
      aux_sym_source_file_repeat1,
    STATE(24), 2,
      sym_definition,
      sym_comment,
  [123] = 1,
    ACTIONS(19), 6,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_LF,
      anon_sym_CR_LF,
  [132] = 3,
    STATE(9), 1,
      aux_sym__terminator,
    ACTIONS(48), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(46), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_POUND,
  [145] = 3,
    STATE(9), 1,
      aux_sym__terminator,
    ACTIONS(53), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_POUND,
  [158] = 3,
    STATE(9), 1,
      aux_sym__terminator,
    ACTIONS(53), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_POUND,
  [171] = 3,
    STATE(9), 1,
      aux_sym__terminator,
    ACTIONS(53), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_POUND,
  [184] = 1,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_LBRACK,
      anon_sym_POUND,
      anon_sym_LF,
      anon_sym_CR_LF,
  [193] = 3,
    ACTIONS(34), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [205] = 4,
    ACTIONS(34), 1,
      anon_sym_POUND,
    STATE(10), 1,
      aux_sym__terminator,
    STATE(21), 1,
      sym_comment,
    ACTIONS(63), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [219] = 3,
    ACTIONS(34), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [231] = 3,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym__terminator,
    ACTIONS(69), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [242] = 4,
    ACTIONS(71), 1,
      aux_sym_definition_token1,
    ACTIONS(73), 1,
      aux_sym_macro_token1,
    STATE(2), 1,
      sym_string,
    STATE(14), 1,
      sym_text,
  [255] = 3,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym__terminator,
    ACTIONS(69), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [266] = 1,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [272] = 2,
    STATE(12), 1,
      aux_sym__terminator,
    ACTIONS(77), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [280] = 3,
    ACTIONS(79), 1,
      aux_sym_macro_token1,
    STATE(2), 1,
      sym_string,
    STATE(16), 1,
      sym_text,
  [290] = 1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [296] = 2,
    STATE(11), 1,
      aux_sym__terminator,
    ACTIONS(69), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [304] = 1,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [310] = 2,
    ACTIONS(79), 1,
      aux_sym_macro_token1,
    STATE(8), 1,
      sym_string,
  [317] = 1,
    ACTIONS(83), 1,
      aux_sym_macro_token1,
  [321] = 1,
    ACTIONS(85), 1,
      aux_sym_format_token1,
  [325] = 1,
    ACTIONS(87), 1,
      anon_sym_COLON,
  [329] = 1,
    ACTIONS(89), 1,
      anon_sym_COLON,
  [333] = 1,
    ACTIONS(91), 1,
      aux_sym_macro_token1,
  [337] = 1,
    ACTIONS(93), 1,
      anon_sym_DOLLAR,
  [341] = 1,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
  [345] = 1,
    ACTIONS(97), 1,
      anon_sym_SPACE,
  [349] = 1,
    ACTIONS(99), 1,
      aux_sym_macro_token1,
  [353] = 1,
    ACTIONS(101), 1,
      aux_sym_expression_token1,
  [357] = 1,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
  [361] = 1,
    ACTIONS(105), 1,
      aux_sym_macro_token1,
  [365] = 1,
    ACTIONS(107), 1,
      aux_sym_format_token2,
  [369] = 1,
    ACTIONS(109), 1,
      anon_sym_POUND_BANG,
  [373] = 1,
    ACTIONS(111), 1,
      aux_sym_macro_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 69,
  [SMALL_STATE(6)] = 87,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 123,
  [SMALL_STATE(9)] = 132,
  [SMALL_STATE(10)] = 145,
  [SMALL_STATE(11)] = 158,
  [SMALL_STATE(12)] = 171,
  [SMALL_STATE(13)] = 184,
  [SMALL_STATE(14)] = 193,
  [SMALL_STATE(15)] = 205,
  [SMALL_STATE(16)] = 219,
  [SMALL_STATE(17)] = 231,
  [SMALL_STATE(18)] = 242,
  [SMALL_STATE(19)] = 255,
  [SMALL_STATE(20)] = 266,
  [SMALL_STATE(21)] = 272,
  [SMALL_STATE(22)] = 280,
  [SMALL_STATE(23)] = 290,
  [SMALL_STATE(24)] = 296,
  [SMALL_STATE(25)] = 304,
  [SMALL_STATE(26)] = 310,
  [SMALL_STATE(27)] = 317,
  [SMALL_STATE(28)] = 321,
  [SMALL_STATE(29)] = 325,
  [SMALL_STATE(30)] = 329,
  [SMALL_STATE(31)] = 333,
  [SMALL_STATE(32)] = 337,
  [SMALL_STATE(33)] = 341,
  [SMALL_STATE(34)] = 345,
  [SMALL_STATE(35)] = 349,
  [SMALL_STATE(36)] = 353,
  [SMALL_STATE(37)] = 357,
  [SMALL_STATE(38)] = 361,
  [SMALL_STATE(39)] = 365,
  [SMALL_STATE(40)] = 369,
  [SMALL_STATE(41)] = 373,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_text, 1, 0, 0), SHIFT(28),
  [14] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 2, 0, 0),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_text, 2, 0, 0), SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__terminator, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__terminator, 2, 0, 0), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_key, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lines, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_key, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [103] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pdx_localization(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pdx_localization",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
